import { computed, unref } from 'vue'

const getAuthPermissions = (auth) => unref(auth?.permissions) || []
const getAuthRoles = (auth) => unref(auth?.roles) || []

export const useAdminDashboardSectionProps = ({
  activeServiceUsers,
  adminAccountLabel,
  apiLogPagination,
  apiLogs,
  auditLogs,
  auth,
  balanceDisplay,
  barWidth,
  canActivateService,
  canDisableService,
  canManageRoles,
  canManageUserStatus,
  canExportIssues,
  canNotifyIssues,
  canReadAudit,
  canReadIssues,
  canReadUsage,
  canReadUsers,
  canReconcileBilling,
  canResetService,
  canUpdateIssues,
  canUpdateServiceLimits,
  cards,
  deleting,
  filteredUsers,
  formatDateTime,
  formatRoleList,
  formatUsd,
  isSelf,
  allVisibleIssuesSelected,
  issueActionLoading,
  issuePagination,
  issueQuery,
  issues,
  lastExport,
  loadingIssueDetail,
  loadingIssues,
  loading302,
  loadingApiLogs,
  loadingLogs,
  loadingOverview,
  loadingRecord,
  loadingUsers,
  log302Query,
  logQuery,
  notEnabledActiveUsers,
  nowLabel,
  pagedUsers,
  pagination,
  pendingBillingUsers,
  recordData,
  recordRequestId,
  reconcilingBilling,
  roleLabel,
  roleOptions,
  saving,
  selectedRoles,
  selectedExportGroupCount,
  selectedExportGroupIds,
  selectedIssue,
  selectedIssueCount,
  selectedIssueIds,
  serviceActivationRate,
  serviceLoadNotice,
  serviceLoading,
  serviceStatusClass,
  serviceStatusLabel,
  showServiceSection,
  showUserActions,
  statusClass,
  statusLabel,
  statusLoading,
  toPrettyJson,
  topModelLabel,
  topSpenders,
  totalUserPages,
  usageSeries,
  userPage,
  userPageEnd,
  userPageStart,
  userSearchQuery,
  userStatusFilter,
  users,
  visibleUserPages
}) => {
  const overviewSectionProps = computed(() => ({
    activeServiceUsers: unref(activeServiceUsers),
    adminAccountLabel: unref(adminAccountLabel),
    barWidth,
    canReadUsage: unref(canReadUsage),
    cards: unref(cards),
    formatRoleList,
    formatUsd,
    loadingOverview: unref(loadingOverview),
    notEnabledActiveUsers: unref(notEnabledActiveUsers),
    nowLabel: unref(nowLabel),
    pendingBillingUsers: unref(pendingBillingUsers),
    permissionCount: getAuthPermissions(auth).length,
    roles: getAuthRoles(auth),
    topSpenders: unref(topSpenders),
    usageSeries: unref(usageSeries)
  }))

  const userServiceSectionProps = computed(() => ({
    searchQuery: unref(userSearchQuery),
    statusFilter: unref(userStatusFilter),
    canActivateService: unref(canActivateService),
    canDisableService: unref(canDisableService),
    canManageRoles: unref(canManageRoles),
    canManageUserStatus: unref(canManageUserStatus),
    canReadUsers: unref(canReadUsers),
    canResetService: unref(canResetService),
    canUpdateServiceLimits: unref(canUpdateServiceLimits),
    deleting: unref(deleting),
    filteredUsers: unref(filteredUsers),
    formatDateTime,
    formatUsd,
    isSelf,
    loadingUsers: unref(loadingUsers),
    notEnabledActiveUsers: unref(notEnabledActiveUsers),
    pagedUsers: unref(pagedUsers),
    pendingBillingUsers: unref(pendingBillingUsers),
    roleLabel,
    roleOptions,
    saving: unref(saving),
    selectedRoles: unref(selectedRoles),
    serviceActivationRate: unref(serviceActivationRate),
    serviceLoading: unref(serviceLoading),
    serviceStatusClass,
    serviceStatusLabel,
    showUserActions: unref(showUserActions),
    statusClass,
    statusLabel,
    statusLoading: unref(statusLoading),
    topModelLabel,
    totalUserPages: unref(totalUserPages),
    userPage: unref(userPage),
    userPageEnd: unref(userPageEnd),
    userPageStart: unref(userPageStart),
    users: unref(users),
    visibleUserPages: unref(visibleUserPages)
  }))

  const serviceReconciliationSectionProps = computed(() => ({
    recordRequestId: unref(recordRequestId),
    activeServiceUsers: unref(activeServiceUsers),
    apiLogPagination: unref(apiLogPagination),
    apiLogs: unref(apiLogs),
    balanceDisplay: unref(balanceDisplay),
    canReadUsage: unref(canReadUsage),
    canReadUsers: unref(canReadUsers),
    canReconcileBilling: unref(canReconcileBilling),
    loading302: unref(loading302),
    loadingApiLogs: unref(loadingApiLogs),
    loadingRecord: unref(loadingRecord),
    log302Query: unref(log302Query),
    recordData: unref(recordData),
    reconcilingBilling: unref(reconcilingBilling),
    serviceLoadNotice: unref(serviceLoadNotice),
    showServiceSection: unref(showServiceSection)
  }))

  const auditLogSectionProps = computed(() => ({
    auditLogs: unref(auditLogs),
    canReadAudit: unref(canReadAudit),
    formatDateTime,
    loadingLogs: unref(loadingLogs),
    logQuery: unref(logQuery),
    pagination: unref(pagination),
    toPrettyJson
  }))

  const issueInboxSectionProps = computed(() => ({
    allVisibleIssuesSelected: unref(allVisibleIssuesSelected),
    canExportIssues: unref(canExportIssues),
    canNotifyIssues: unref(canNotifyIssues),
    canReadIssues: unref(canReadIssues),
    canUpdateIssues: unref(canUpdateIssues),
    formatDateTime,
    issueActionLoading: unref(issueActionLoading),
    issuePagination: unref(issuePagination),
    issueQuery: unref(issueQuery),
    issues: unref(issues),
    lastExport: unref(lastExport),
    loadingIssueDetail: unref(loadingIssueDetail),
    loadingIssues: unref(loadingIssues),
    selectedExportGroupCount: unref(selectedExportGroupCount),
    selectedExportGroupIds: unref(selectedExportGroupIds),
    selectedIssue: unref(selectedIssue),
    selectedIssueCount: unref(selectedIssueCount),
    selectedIssueIds: unref(selectedIssueIds),
    toPrettyJson
  }))

  return {
    auditLogSectionProps,
    issueInboxSectionProps,
    overviewSectionProps,
    serviceReconciliationSectionProps,
    userServiceSectionProps
  }
}

export default useAdminDashboardSectionProps
