import { useAdminDashboardSectionProps } from './useAdminDashboardSectionProps'

export const useAdminUsersDashboardSections = ({
  accessState,
  usersState,
  dashboardData,
  displayState,
  serviceOps,
  userActions,
  auth
}) => useAdminDashboardSectionProps({
  activeServiceUsers: usersState.activeServiceUsers,
  adminAccountLabel: accessState.adminAccountLabel,
  apiLogs: serviceOps.apiLogs,
  auditLogs: dashboardData.auditLogs,
  auth,
  balanceDisplay: serviceOps.balanceDisplay,
  barWidth: dashboardData.barWidth,
  canActivateService: accessState.canActivateService,
  canDisableService: accessState.canDisableService,
  canManageRoles: accessState.canManageRoles,
  canManageUserStatus: accessState.canManageUserStatus,
  canReadAudit: accessState.canReadAudit,
  canReadUsage: accessState.canReadUsage,
  canReadUsers: accessState.canReadUsers,
  canReconcileBilling: accessState.canReconcileBilling,
  canResetService: accessState.canResetService,
  canUpdateServiceLimits: accessState.canUpdateServiceLimits,
  cards: displayState.cards,
  deleting: userActions.deleting,
  filteredUsers: usersState.filteredUsers,
  formatDateTime: displayState.formatDateTime,
  formatRoleList: displayState.formatRoleList,
  formatUsd: displayState.formatUsd,
  isSelf: accessState.isSelf,
  loading302: serviceOps.loading302,
  loadingApiLogs: serviceOps.loadingApiLogs,
  loadingLogs: dashboardData.loadingLogs,
  loadingOverview: dashboardData.loadingOverview,
  loadingRecord: serviceOps.loadingRecord,
  loadingUsers: usersState.loadingUsers,
  log302Query: serviceOps.log302Query,
  logQuery: dashboardData.logQuery,
  notEnabledActiveUsers: usersState.notEnabledActiveUsers,
  nowLabel: displayState.nowLabel,
  pagedUsers: usersState.pagedUsers,
  pagination: dashboardData.pagination,
  pendingBillingUsers: usersState.pendingBillingUsers,
  recordData: serviceOps.recordData,
  recordRequestId: serviceOps.recordRequestId,
  reconcilingBilling: userActions.reconcilingBilling,
  roleLabel: displayState.roleLabel,
  roleOptions: displayState.roleOptions,
  saving: userActions.saving,
  selectedRoles: usersState.selectedRoles,
  serviceActivationRate: usersState.serviceActivationRate,
  serviceLoadNotice: serviceOps.serviceLoadNotice,
  serviceLoading: userActions.serviceLoading,
  serviceStatusClass: displayState.serviceStatusClass,
  serviceStatusLabel: displayState.serviceStatusLabel,
  showServiceSection: accessState.showServiceSection,
  showUserActions: accessState.showUserActions,
  statusClass: displayState.statusClass,
  statusLabel: displayState.statusLabel,
  statusLoading: userActions.statusLoading,
  toPrettyJson: displayState.toPrettyJson,
  topModelLabel: displayState.topModelLabel,
  topSpenders: usersState.topSpenders,
  totalUserPages: usersState.totalUserPages,
  usageSeries: dashboardData.usageSeries,
  userPage: usersState.userPage,
  userPageEnd: usersState.userPageEnd,
  userPageStart: usersState.userPageStart,
  userSearchQuery: usersState.userSearchQuery,
  userStatusFilter: usersState.userStatusFilter,
  users: usersState.users,
  visibleUserPages: usersState.visibleUserPages
})

export default useAdminUsersDashboardSections
