import assert from 'node:assert/strict'
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { test } from 'node:test'

const canvasSource = readFileSync(new URL('./Canvas.vue', import.meta.url), 'utf8')
const globalStyleSource = readFileSync(new URL('../style.css', import.meta.url), 'utf8')

function readComponentSource(name) {
  const url = new URL(`../components/canvas/${name}.vue`, import.meta.url)
  const path = fileURLToPath(url)
  return existsSync(path) ? readFileSync(url, 'utf8') : ''
}

function readHookSource(name) {
  const url = new URL(`../hooks/${name}.js`, import.meta.url)
  const path = fileURLToPath(url)
  return existsSync(path) ? readFileSync(url, 'utf8') : ''
}

function countLines(source) {
  return source.split(/\r?\n/).length
}

test('canvas extracted components and composables stay below the focused module line ceiling', () => {
  const canvasComponentEntries = readdirSync(new URL('../components/canvas/', import.meta.url), { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.vue'))
    .map((entry) => ({
      name: `components/canvas/${entry.name}`,
      lines: countLines(readFileSync(new URL(`../components/canvas/${entry.name}`, import.meta.url), 'utf8'))
    }))
  const canvasComposableEntries = readdirSync(new URL('../hooks/', import.meta.url), { withFileTypes: true })
    .filter((entry) => entry.isFile() && /^useCanvas.*\.js$/.test(entry.name) && !entry.name.endsWith('.test.js'))
    .map((entry) => ({
      name: `hooks/${entry.name}`,
      lines: countLines(readFileSync(new URL(`../hooks/${entry.name}`, import.meta.url), 'utf8'))
    }))
  const oversized = [...canvasComponentEntries, ...canvasComposableEntries]
    .filter((entry) => entry.lines >= 400)

  assert.equal(countLines(canvasSource) < 850, true, 'Canvas.vue should stay below 850 lines')
  assert.deepEqual(oversized, [])
})

test('canvas chrome uses scoped control components instead of global UI classes', () => {
  const surfaceSource = readComponentSource('CanvasSurface')
  const pillButtonSource = readComponentSource('CanvasPillButton')
  const iconButtonSource = readComponentSource('CanvasIconButton')
  const toolbarButtonSource = readComponentSource('CanvasToolbarButton')

  for (const oldClass of ['flora-panel', 'ui-pill-button', 'ui-icon-button', 'ui-toolbar-button']) {
    assert.doesNotMatch(canvasSource, new RegExp(oldClass))
    assert.doesNotMatch(globalStyleSource, new RegExp(`\\.${oldClass}(?:\\s|\\.|:|\\{)`))
  }

  assert.match(surfaceSource, /<component\s+:is="as"\s+class="canvas-surface"/)
  assert.match(surfaceSource, /\.canvas-surface\s*\{[^}]*backdrop-filter:\s*var\(--surface-blur\)/s)
  assert.match(pillButtonSource, /<button\s+type="button"\s+class="canvas-pill-button"/)
  assert.match(pillButtonSource, /canvas-pill-button--compact/)
  assert.match(iconButtonSource, /<button\s+type="button"\s+class="canvas-icon-button"/)
  assert.match(iconButtonSource, /\.canvas-icon-button:disabled\s*\{/)
  assert.match(toolbarButtonSource, /<button\s+type="button"\s+class="canvas-toolbar-button"/)
  assert.match(toolbarButtonSource, /canvas-toolbar-button--round/)
})

test('canvas view delegates page chrome to focused feature components', () => {
  const topControlsSource = readComponentSource('CanvasTopControls')
  const toolbarSource = readComponentSource('CanvasToolbar')
  const zoomControlsSource = readComponentSource('CanvasZoomControls')

  assert.match(canvasSource, /import CanvasTopControls from '@\/components\/canvas\/CanvasTopControls\.vue'/)
  assert.match(canvasSource, /import CanvasToolbar from '@\/components\/canvas\/CanvasToolbar\.vue'/)
  assert.match(canvasSource, /import CanvasZoomControls from '@\/components\/canvas\/CanvasZoomControls\.vue'/)
  assert.equal([...canvasSource.matchAll(/<CanvasTopControls\b/g)].length, 1)
  assert.equal([...canvasSource.matchAll(/<CanvasToolbar\b/g)].length, 1)
  assert.equal([...canvasSource.matchAll(/<CanvasZoomControls\b/g)].length, 1)
  assert.doesNotMatch(canvasSource, /<CanvasPillButton\b/)
  assert.doesNotMatch(canvasSource, /<CanvasToolbarButton\b/)
  assert.doesNotMatch(canvasSource, /<CanvasIconButton\b/)

  assert.match(topControlsSource, /defineEmits\(\['workspace', 'project-action', 'remote-refresh', 'share', 'request-edit'\]\)/)
  assert.match(topControlsSource, /<BaseDropdown\s+:options="projectOptions"\s+compact\s+@select="\$emit\('project-action', \$event\)"/)
  assert.match(topControlsSource, /<CanvasPillButton/)
  assert.match(toolbarSource, /defineEmits\(\['add-node', 'open-library', 'undo', 'redo', 'open-api-settings', 'inject-image', 'upload-avatar'\]\)/)
  assert.match(toolbarSource, /:disabled="readOnly \|\| !canUndo"/)
  assert.match(toolbarSource, /:disabled="readOnly \|\| !canRedo"/)
  assert.match(toolbarSource, /<CanvasToolbarButton/)
  assert.match(zoomControlsSource, /defineEmits\(\['fit-view', 'zoom-out', 'zoom-in'\]\)/)
  assert.match(zoomControlsSource, /\{\{ zoomPercent \}\}%/)
  assert.match(zoomControlsSource, /<CanvasIconButton/)
})

test('canvas bootstraps auth before loading project drafts', () => {
  const routeLifecycleSource = readHookSource('useCanvasRouteLifecycle')

  assert.match(canvasSource, /import \{ useAuthStore \} from '@\/stores\/auth'/)
  assert.match(canvasSource, /const \{[^}]*bootstrapAuth[^}]*\} = useAuthStore\(\)/)
  assert.match(canvasSource, /useCanvasRouteLifecycle\(\{/)
  assert.match(canvasSource, /\sbootstrapAuth,/)
  assert.match(canvasSource, /\sloadCachedProjects,/)

  const mountedStart = routeLifecycleSource.indexOf('onMountedFn(async () => {')
  const bootstrapIndex = routeLifecycleSource.indexOf('await bootstrapAuth()', mountedStart)
  const loadCachedIndex = routeLifecycleSource.indexOf('await loadCachedProjects()', mountedStart)

  assert.ok(mountedStart >= 0)
  assert.ok(bootstrapIndex > mountedStart)
  assert.ok(loadCachedIndex > mountedStart)
  assert.ok(bootstrapIndex < loadCachedIndex)
})

test('canvas view delegates the Vue Flow stage to a focused component', () => {
  const flowStageSource = readComponentSource('CanvasFlowStage')

  assert.match(canvasSource, /import CanvasFlowStage from '@\/components\/canvas\/CanvasFlowStage\.vue'/)
  assert.equal([...canvasSource.matchAll(/<CanvasFlowStage\b/g)].length, 1)
  assert.match(canvasSource, /:key="flowKey"/)
  assert.match(canvasSource, /v-model:nodes="nodes"/)
  assert.match(canvasSource, /v-model:edges="edges"/)
  assert.match(canvasSource, /v-model:viewport="viewport"/)
  assert.match(canvasSource, /:node-types="nodeTypes"/)
  assert.match(canvasSource, /:edge-types="edgeTypes"/)
  assert.match(canvasSource, /:default-viewport="canvasViewport"/)
  assert.match(canvasSource, /:canvas-flow-style="canvasFlowStyle"/)
  assert.match(canvasSource, /@connect-start="onConnectStart"/)
  assert.match(canvasSource, /@viewport-change="handleViewportChange"/)
  assert.match(canvasSource, /@edges-change="onEdgesChange"/)
  assert.doesNotMatch(canvasSource, /<VueFlow\b/)
  assert.doesNotMatch(canvasSource, /import \{ VueFlow, useVueFlow \} from '@vue-flow\/core'/)

  assert.match(flowStageSource, /import \{ computed \} from 'vue'/)
  assert.match(flowStageSource, /import \{ VueFlow \} from '@vue-flow\/core'/)
  assert.match(flowStageSource, /<VueFlow/)
  assert.match(flowStageSource, /v-model:nodes="nodesModel"/)
  assert.match(flowStageSource, /v-model:edges="edgesModel"/)
  assert.match(flowStageSource, /v-model:viewport="viewportModel"/)
  assert.match(flowStageSource, /:min-zoom="0\.1"/)
  assert.match(flowStageSource, /:max-zoom="2"/)
  assert.match(flowStageSource, /:snap-grid="\[20, 20\]"/)
  assert.match(flowStageSource, /multi-selection-key-code="Shift"/)
  assert.match(flowStageSource, /class="canvas-flow"/)
  assert.match(flowStageSource, /:nodes-draggable="!readOnly"/)
  assert.match(flowStageSource, /@connect="emitMutable\('connect', \$event\)"/)
  assert.match(flowStageSource, /@viewport-change="\$emit\('viewportChange', \$event\)"/)
})

test('canvas view wires local media drag and drop through the focused composable', () => {
  assert.match(canvasSource, /import \{ useCanvasMediaDrop \} from '@\/hooks\/useCanvasMediaDrop\.js'/)
  assert.match(canvasSource, /import \{ isExpiredRemoteUrl, uploadImageFile \} from '@\/utils\/media'/)
  assert.match(canvasSource, /@dragover="handleCanvasMediaDragOver"/)
  assert.match(canvasSource, /@drop="handleCanvasMediaDropGuarded"/)
  assert.match(canvasSource, /useCanvasMediaDrop\(\{/)
  assert.match(canvasSource, /\saddNode,/)
  assert.match(canvasSource, /\scurrentProjectId: currentCanvasProjectId,/)
  assert.match(canvasSource, /\sflushSave,/)
  assert.match(canvasSource, /\supdateNode,/)
  assert.match(canvasSource, /\suploadMediaFile: uploadImageFile,/)
  assert.match(canvasSource, /\sviewport/)
})

test('canvas view delegates viewport interaction to a focused composable', () => {
  const viewportInteractionSource = readHookSource('useCanvasViewportInteraction')

  assert.match(canvasSource, /import \{ useCanvasViewportInteraction \} from '@\/hooks\/useCanvasViewportInteraction\.js'/)
  assert.match(canvasSource, /useCanvasViewportInteraction\(\{/)
  assert.match(canvasSource, /handleViewportChange\s*}/)
  assert.match(canvasSource, /clearViewportSettleTimer,/)
  assert.match(canvasSource, /canvasFlowStyle/)
  assert.doesNotMatch(canvasSource, /let viewportSettleTimeoutId = null/)
  assert.doesNotMatch(canvasSource, /const buildCanvasFlowStyle = \(sourceViewport = viewport\.value\) =>/)
  assert.doesNotMatch(canvasSource, /const settledCanvasFlowStyle = ref\(buildCanvasFlowStyle\(\)\)/)
  assert.doesNotMatch(canvasSource, /const handleViewportChange = \(newViewport\) =>/)
  assert.doesNotMatch(canvasSource, /const clearViewportSettleTimer = \(\) =>/)

  assert.match(viewportInteractionSource, /import \{ computed, ref \} from 'vue'/)
  assert.match(viewportInteractionSource, /export const useCanvasViewportInteraction = \(/)
  assert.match(viewportInteractionSource, /getNodeCapsuleScale\(zoom\)/)
  assert.match(viewportInteractionSource, /recordPerf\('viewport-change'/)
  assert.match(viewportInteractionSource, /setTimeoutFn\(\(\) => \{/)
  assert.match(viewportInteractionSource, /clearViewportSettleTimer/)
})

test('canvas view delegates selection and keyboard interaction to a focused composable', () => {
  const selectionInteractionSource = readHookSource('useCanvasSelectionInteraction')

  assert.match(canvasSource, /import \{ useCanvasSelectionInteraction \} from '@\/hooks\/useCanvasSelectionInteraction\.js'/)
  assert.match(canvasSource, /useCanvasSelectionInteraction\(\{/)
  assert.match(canvasSource, /selectedNodeIds,/)
  assert.match(canvasSource, /handleGlobalKeydown/)
  assert.doesNotMatch(canvasSource, /const selectedNodeIds = computed\(\(\) =>/)
  assert.doesNotMatch(canvasSource, /const clearNodeSelection = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const clearGroupSelection = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const syncNodeSelectedState = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const onNodeClick = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const onPaneClick = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const isTypingElement = \(target\) =>/)
  assert.doesNotMatch(canvasSource, /const removeSelectedElements = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const handleGlobalKeydown = \(event\) =>/)

  assert.match(selectionInteractionSource, /import \{ computed \} from 'vue'/)
  assert.match(selectionInteractionSource, /export const useCanvasSelectionInteraction = \(/)
  assert.match(selectionInteractionSource, /const selectedNodeIds = computed/)
  assert.match(selectionInteractionSource, /const syncNodeSelectedState = \(\) =>/)
  assert.match(selectionInteractionSource, /const onPaneClick = \(\) =>/)
  assert.match(selectionInteractionSource, /const handleGlobalKeydown = \(event\) =>/)
})

test('canvas view delegates node drag and node change interaction to a focused composable', () => {
  const nodeDragInteractionSource = readHookSource('useCanvasNodeDragInteraction')

  assert.match(canvasSource, /import \{ useCanvasNodeDragInteraction \} from '@\/hooks\/useCanvasNodeDragInteraction\.js'/)
  assert.match(canvasSource, /useCanvasNodeDragInteraction\(\{/)
  assert.match(canvasSource, /onNodeDragStart,/)
  assert.match(canvasSource, /onNodeDragStop,/)
  assert.match(canvasSource, /onNodesChange/)
  assert.doesNotMatch(canvasSource, /let nodeDragMoved = false/)
  assert.doesNotMatch(canvasSource, /let groupedNodeDragState = null/)
  assert.doesNotMatch(canvasSource, /const findGroupByNodeId = \(nodeId\) =>/)
  assert.doesNotMatch(canvasSource, /const startGroupedNodeDrag = \(nodeId\) =>/)
  assert.doesNotMatch(canvasSource, /const applyGroupedNodeDragDelta = \(changes = \[\]\) =>/)
  assert.doesNotMatch(canvasSource, /const onNodeDragStart = \(_, node\) =>/)
  assert.doesNotMatch(canvasSource, /const onNodeDragStop = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const isPositionOnlyChangeBatch = \(changes = \[\]\) =>/)
  assert.doesNotMatch(canvasSource, /const onNodesChange = \(changes = \[\]\) =>/)

  assert.match(nodeDragInteractionSource, /import \{ nextTick \} from 'vue'/)
  assert.match(nodeDragInteractionSource, /export const useCanvasNodeDragInteraction = \(/)
  assert.match(nodeDragInteractionSource, /const startGroupedNodeDrag = \(nodeId\) =>/)
  assert.match(nodeDragInteractionSource, /const applyGroupedNodeDragDelta = \(changes = \[\]\) =>/)
  assert.match(nodeDragInteractionSource, /const onNodeDragStart = \(_, node\) =>/)
  assert.match(nodeDragInteractionSource, /const onNodeDragStop = \(\) =>/)
  assert.match(nodeDragInteractionSource, /const onNodesChange = \(changes = \[\]\) =>/)
})

test('canvas view delegates connection and context menu interaction to a focused composable', () => {
  const connectionInteractionSource = readHookSource('useCanvasConnectionInteraction')

  assert.match(canvasSource, /import \{ useCanvasConnectionInteraction \} from '@\/hooks\/useCanvasConnectionInteraction\.js'/)
  assert.match(canvasSource, /useCanvasConnectionInteraction\(\{/)
  assert.match(canvasSource, /onConnect,/)
  assert.match(canvasSource, /onConnectStart,/)
  assert.match(canvasSource, /onConnectEnd,/)
  assert.match(canvasSource, /onEdgesChange,/)
  assert.match(canvasSource, /onPaneContextMenu,/)
  assert.match(canvasSource, /handleCanvasContextMenu/)
  assert.doesNotMatch(canvasSource, /const shouldIgnoreCanvasContextMenuTarget = \(target\) =>/)
  assert.doesNotMatch(canvasSource, /const onConnect = \(params\) =>/)
  assert.doesNotMatch(canvasSource, /const pendingConnect = ref\(null\)/)
  assert.doesNotMatch(canvasSource, /const connectSucceeded = ref\(false\)/)
  assert.doesNotMatch(canvasSource, /const readPointer = \(eventLike\) =>/)
  assert.doesNotMatch(canvasSource, /const onConnectStart = \(params\) =>/)
  assert.doesNotMatch(canvasSource, /const onConnectEnd = \(event\) =>/)
  assert.doesNotMatch(canvasSource, /const onEdgesChange = \(changes\) =>/)
  assert.doesNotMatch(canvasSource, /const onPaneContextMenu = \(event\) =>/)
  assert.doesNotMatch(canvasSource, /const handleCanvasContextMenu = \(event\) =>/)

  assert.match(connectionInteractionSource, /import \{ nextTick, ref \} from 'vue'/)
  assert.match(connectionInteractionSource, /export const useCanvasConnectionInteraction = \(/)
  assert.match(connectionInteractionSource, /const shouldIgnoreCanvasContextMenuTarget = \(target\) =>/)
  assert.match(connectionInteractionSource, /const onConnect = \(params\) =>/)
  assert.match(connectionInteractionSource, /const onConnectStart = \(params\) =>/)
  assert.match(connectionInteractionSource, /const onConnectEnd = \(event\) =>/)
  assert.match(connectionInteractionSource, /const onEdgesChange = \(changes = \[\]\) =>/)
  assert.match(connectionInteractionSource, /const handleCanvasContextMenu = \(event\) =>/)
})

test('canvas feature styles live with their owning components', () => {
  const flowStageSource = readComponentSource('CanvasFlowStage')
  const topControlsSource = readComponentSource('CanvasTopControls')
  const toolbarSource = readComponentSource('CanvasToolbar')
  const zoomControlsSource = readComponentSource('CanvasZoomControls')

  assert.doesNotMatch(canvasSource, /@import '@vue-flow\/core\/dist\/style\.css'/)
  assert.doesNotMatch(canvasSource, /@import '@vue-flow\/core\/dist\/theme-default\.css'/)
  assert.doesNotMatch(canvasSource, /\.canvas-flow\b/)
  assert.doesNotMatch(canvasSource, /\.canvas-primary-tool\b/)
  assert.doesNotMatch(canvasSource, /\.canvas-sync-pill\b/)
  assert.doesNotMatch(canvasSource, /\.canvas-sync-refresh-btn\b/)
  assert.doesNotMatch(canvasSource, /\.canvas-zoom-pill\b/)

  assert.match(flowStageSource, /@import '@vue-flow\/core\/dist\/style\.css';/)
  assert.match(flowStageSource, /@import '@vue-flow\/core\/dist\/theme-default\.css';/)
  assert.match(flowStageSource, /\.canvas-flow\s*\{[^}]*width:\s*100%;[^}]*height:\s*100%;[^}]*background:\s*#080808;/s)
  assert.match(flowStageSource, /\.canvas-flow \.vue-flow__pane\s*\{/)
  assert.match(flowStageSource, /\.canvas-flow \.vue-flow__edge\.selected \.vue-flow__edge-path\s*\{/)
  assert.match(toolbarSource, /\.canvas-primary-tool\s*\{/)
  assert.match(topControlsSource, /\.canvas-sync-pill\s*\{/)
  assert.match(topControlsSource, /\.canvas-sync-refresh-btn:hover:not\(:disabled\)\s*\{/)
  assert.match(zoomControlsSource, /\.canvas-zoom-pill\s*\{/)
})

test('canvas view delegates group overlay chrome to a focused component', () => {
  const groupOverlaySource = readComponentSource('CanvasGroupOverlay')
  const groupCreateMenuSource = readComponentSource('CanvasGroupCreateMenu')
  const groupActionsMenuSource = readComponentSource('CanvasGroupActionsMenu')
  const groupFloatingMenuSource = readComponentSource('CanvasGroupFloatingMenu')
  const groupBoxSource = readComponentSource('CanvasGroupBox')
  const groupEdgeSource = readComponentSource('CanvasGroupEdge')

  assert.match(canvasSource, /import CanvasGroupOverlay from '@\/components\/canvas\/CanvasGroupOverlay\.vue'/)
  assert.match(canvasSource, /import \{ useCanvasGroupActions \} from '@\/hooks\/useCanvasGroupActions\.js'/)
  assert.match(canvasSource, /import \{ useCanvasGroupDrag \} from '@\/hooks\/useCanvasGroupDrag\.js'/)
  assert.match(canvasSource, /import \{ useCanvasOverlayRects \} from '@\/hooks\/useCanvasOverlayRects\.js'/)
  assert.match(canvasSource, /useCanvasGroupActions\(\{/)
  assert.match(canvasSource, /useCanvasGroupDrag\(\{/)
  assert.match(canvasSource, /useCanvasOverlayRects\(\{/)
  assert.equal([...canvasSource.matchAll(/<CanvasGroupOverlay\b/g)].length, 1)
  assert.match(canvasSource, /:multi-select-menu-rect="multiSelectMenuRect"/)
  assert.match(canvasSource, /:rendered-groups="renderedGroups"/)
  assert.match(canvasSource, /:selected-group-id="selectedGroupId"/)
  assert.match(canvasSource, /:selected-group-menu-rect="selectedGroupMenuRect"/)
  assert.match(canvasSource, /:group-body-hit-rects-by-id="groupBodyHitRectsById"/)
  assert.match(canvasSource, /@create-group="handleCreateGroup"/)
  assert.match(canvasSource, /@group-grip-pointer-down="handleGroupGripPointerDown"/)
  assert.match(canvasSource, /@select-group="selectGroup"/)
  assert.match(canvasSource, /@rename-group="openRenameGroupModal"/)
  assert.match(canvasSource, /@duplicate-selected-group="handleDuplicateSelectedGroup"/)
  assert.match(canvasSource, /@ungroup-selected-group="handleUngroupSelectedGroup"/)
  assert.match(canvasSource, /@delete-selected-group="handleDeleteSelectedGroup"/)
  assert.doesNotMatch(canvasSource, /const handleCreateGroup = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const openRenameGroupModal = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const confirmRenameGroup = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const handleDuplicateSelectedGroup = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const handleUngroupSelectedGroup = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const handleDeleteSelectedGroup = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const startGroupDrag = \(group, event\) =>/)
  assert.doesNotMatch(canvasSource, /const handleGroupDragMove = \(event\) =>/)
  assert.doesNotMatch(canvasSource, /const stopGroupDrag = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const updateOverlayRects = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const selectedGroupBodyHitRects = computed/)
  assert.doesNotMatch(canvasSource, /let overlayRafId = null/)
  assert.doesNotMatch(canvasSource, /class="group-overlay-layer"/)
  assert.doesNotMatch(canvasSource, /class="canvas-group-box"/)

  assert.match(groupOverlaySource, /import CanvasGroupCreateMenu from '\.\/CanvasGroupCreateMenu\.vue'/)
  assert.match(groupOverlaySource, /import CanvasGroupActionsMenu from '\.\/CanvasGroupActionsMenu\.vue'/)
  assert.match(groupOverlaySource, /import CanvasGroupBox from '\.\/CanvasGroupBox\.vue'/)
  assert.doesNotMatch(groupOverlaySource, /import \{ NIcon \} from 'naive-ui'/)
  assert.doesNotMatch(groupOverlaySource, /AppsOutline/)
  assert.match(groupOverlaySource, /defineEmits\(\[\s*'createGroup'/s)
  assert.match(groupOverlaySource, /<div class="group-overlay-layer">/)
  assert.match(groupOverlaySource, /<CanvasGroupCreateMenu\s+v-if="!readOnly"\s+:rect="multiSelectMenuRect"/)
  assert.match(groupOverlaySource, /<CanvasGroupBox\s+v-for="group in renderedGroups"/)
  assert.match(groupOverlaySource, /:hit-rects="groupBodyHitRectsById\[group\.id\] \|\| \[\]"/)
  assert.match(groupOverlaySource, /<CanvasGroupActionsMenu\s+v-if="!readOnly"\s+:rect="selectedGroupMenuRect"/)
  assert.match(groupOverlaySource, /@create-group="\$emit\('createGroup'\)"/)
  assert.match(groupOverlaySource, /@group-grip-pointer-down="!readOnly && \$emit\('groupGripPointerDown', group, \$event\)"/)
  assert.match(groupOverlaySource, /@select-group="!readOnly && \$emit\('selectGroup', \$event\)"/)
  assert.match(groupOverlaySource, /@rename-group="\$emit\('renameGroup'\)"/)
  assert.match(groupOverlaySource, /\.group-overlay-layer\s*\{/)
  assert.doesNotMatch(groupOverlaySource, /class="canvas-group-box"/)
  assert.doesNotMatch(groupOverlaySource, /\.canvas-group-box\s*\{/)
  assert.doesNotMatch(groupOverlaySource, /class="capsule-icon/)

  assert.match(groupCreateMenuSource, /import \{ NIcon \} from 'naive-ui'/)
  assert.match(groupCreateMenuSource, /import CanvasGroupFloatingMenu from '\.\/CanvasGroupFloatingMenu\.vue'/)
  assert.match(groupCreateMenuSource, /AppsOutline/)
  assert.match(groupCreateMenuSource, /defineEmits\(\['createGroup'\]\)/)
  assert.match(groupCreateMenuSource, /<CanvasGroupFloatingMenu\s+:rect="rect"/)
  assert.match(groupCreateMenuSource, /@click="\$emit\('createGroup'\)"/)
  assert.doesNotMatch(groupCreateMenuSource, /class="capsule-menu group-capsule-menu"/)
  assert.doesNotMatch(groupCreateMenuSource, /\.group-capsule-menu\s*\{/)
  assert.doesNotMatch(groupCreateMenuSource, /\.capsule-icon:hover:not\(:disabled\)\s*\{/)
  assert.doesNotMatch(groupCreateMenuSource, /\.group-primary-btn\s*\{/)

  assert.match(groupBoxSource, /defineEmits\(\['groupGripPointerDown', 'selectGroup'\]\)/)
  assert.match(groupOverlaySource, /v-for="group in renderedGroups"/)
  assert.match(groupBoxSource, /v-for="\(hitRect, hitIndex\) in hitRects"/)
  assert.match(groupBoxSource, /@pointerdown="\$emit\('groupGripPointerDown', \$event\)"/)
  assert.match(groupBoxSource, /@click\.stop="\$emit\('selectGroup', group\.id\)"/)
  assert.match(groupBoxSource, /\.canvas-group-box\s*\{/)
  assert.match(groupBoxSource, /import CanvasGroupEdge from '\.\/CanvasGroupEdge\.vue'/)
  assert.match(groupBoxSource, /const groupEdges = \['top', 'right', 'bottom', 'left'\]/)
  assert.match(groupBoxSource, /<CanvasGroupEdge\s+v-for="edge in groupEdges"/)
  assert.match(groupBoxSource, /:edge="edge"/)
  assert.match(groupBoxSource, /@group-grip-pointer-down="\$emit\('groupGripPointerDown', \$event\)"/)
  assert.match(groupBoxSource, /@select-group="\$emit\('selectGroup', group\.id\)"/)
  assert.doesNotMatch(groupBoxSource, /<button class="canvas-group-edge top"/)
  assert.doesNotMatch(groupBoxSource, /\.canvas-group-edge\.right\s*\{/)

  assert.match(groupEdgeSource, /defineProps\(\{[\s\S]*edge:[\s\S]*type: String/s)
  assert.match(groupEdgeSource, /defineEmits\(\['groupGripPointerDown', 'selectGroup'\]\)/)
  assert.match(groupEdgeSource, /:class="edge"/)
  assert.match(groupEdgeSource, /@pointerdown="\$emit\('groupGripPointerDown', \$event\)"/)
  assert.match(groupEdgeSource, /@mousedown="\$emit\('groupGripPointerDown', \$event\)"/)
  assert.match(groupEdgeSource, /@click\.stop="\$emit\('selectGroup'\)"/)
  assert.match(groupEdgeSource, /\.canvas-group-edge\s*\{/)
  assert.match(groupEdgeSource, /\.canvas-group-edge\.right\s*\{/)

  assert.match(groupActionsMenuSource, /import \{ NIcon \} from 'naive-ui'/)
  assert.match(groupActionsMenuSource, /import CanvasGroupFloatingMenu from '\.\/CanvasGroupFloatingMenu\.vue'/)
  assert.match(groupActionsMenuSource, /CreateOutline/)
  assert.match(groupActionsMenuSource, /TrashOutline/)
  assert.match(groupActionsMenuSource, /defineEmits\(\['renameGroup', 'duplicateSelectedGroup', 'ungroupSelectedGroup', 'deleteSelectedGroup'\]\)/)
  assert.match(groupActionsMenuSource, /<CanvasGroupFloatingMenu\s+:rect="rect"/)
  assert.match(groupActionsMenuSource, /@click="\$emit\('renameGroup'\)"/)
  assert.match(groupActionsMenuSource, /@click="\$emit\('deleteSelectedGroup'\)"/)
  assert.doesNotMatch(groupActionsMenuSource, /class="capsule-menu group-capsule-menu"/)
  assert.doesNotMatch(groupActionsMenuSource, /\.group-capsule-menu\s*\{/)
  assert.doesNotMatch(groupActionsMenuSource, /\.capsule-icon:hover:not\(:disabled\)\s*\{/)
  assert.doesNotMatch(groupActionsMenuSource, /\.group-danger-icon:hover:not\(:disabled\)\s*\{/)

  assert.match(groupFloatingMenuSource, /v-if="rect"/)
  assert.match(groupFloatingMenuSource, /class="capsule-menu group-capsule-menu"/)
  assert.match(groupFloatingMenuSource, /<slot \/>/)
  assert.match(groupFloatingMenuSource, /\.group-capsule-menu\s*\{/)
  assert.match(groupFloatingMenuSource, /\.group-capsule-menu \.capsule-inner\s*\{/)
  assert.match(groupFloatingMenuSource, /:deep\(\.capsule-icon\)\s*\{/)
  assert.match(groupFloatingMenuSource, /:deep\(\.capsule-icon:hover:not\(:disabled\)\)\s*\{/)
  assert.match(groupFloatingMenuSource, /:deep\(\.group-danger-icon:hover:not\(:disabled\)\)\s*\{/)
})

test('canvas view delegates node creation menu to a focused component', () => {
  const nodeMenuSource = readComponentSource('CanvasNodeMenu')
  const nodeMenuHeaderSource = readComponentSource('CanvasNodeMenuHeader')
  const nodeTypeListSource = readComponentSource('CanvasNodeTypeList')
  const nodeMenuQuantitySource = readComponentSource('CanvasNodeMenuQuantity')

  assert.match(canvasSource, /import CanvasNodeMenu from '@\/components\/canvas\/CanvasNodeMenu\.vue'/)
  assert.match(canvasSource, /import \{ useCanvasNodeMenuState \} from '@\/hooks\/useCanvasNodeMenuState\.js'/)
  assert.match(canvasSource, /useCanvasNodeMenuState\(\{/)
  assert.equal([...canvasSource.matchAll(/<CanvasNodeMenu\b/g)].length, 1)
  assert.match(canvasSource, /:show="!isReadOnlyProject && showNodeMenu"/)
  assert.match(canvasSource, /:mode="nodeMenuMode"/)
  assert.match(canvasSource, /:menu-style="nodeMenuStyle"/)
  assert.match(canvasSource, /:title="nodeMenuTitle"/)
  assert.match(canvasSource, /:copy="nodeMenuCopy"/)
  assert.match(canvasSource, /:node-types="nodeTypeOptions"/)
  assert.match(canvasSource, /:count="nodeCreateCount"/)
  assert.match(canvasSource, /@select-node-type="addNewNode"/)
  assert.match(canvasSource, /@decrease-count="decreaseNodeCount"/)
  assert.match(canvasSource, /@increase-count="increaseNodeCount"/)
  assert.doesNotMatch(canvasSource, /import \{ NIcon \} from 'naive-ui'/)
  assert.doesNotMatch(canvasSource, /ImageOutline/)
  assert.doesNotMatch(canvasSource, /TextOutline/)
  assert.doesNotMatch(canvasSource, /VideocamOutline/)
  assert.doesNotMatch(canvasSource, /class="node-menu-/)
  assert.doesNotMatch(canvasSource, /const nodeTypeOptions = \[/)
  assert.doesNotMatch(canvasSource, /const nodeMenuTitle = computed/)
  assert.doesNotMatch(canvasSource, /const nodeMenuCopy = computed/)
  assert.doesNotMatch(canvasSource, /const nodeMenuStyle = computed/)

  assert.match(nodeMenuSource, /import CanvasSurface from '\.\/CanvasSurface\.vue'/)
  assert.match(nodeMenuSource, /import CanvasNodeMenuHeader from '\.\/CanvasNodeMenuHeader\.vue'/)
  assert.match(nodeMenuSource, /import CanvasNodeTypeList from '\.\/CanvasNodeTypeList\.vue'/)
  assert.match(nodeMenuSource, /import CanvasNodeMenuQuantity from '\.\/CanvasNodeMenuQuantity\.vue'/)
  assert.doesNotMatch(nodeMenuSource, /import \{ NIcon \} from 'naive-ui'/)
  assert.doesNotMatch(nodeMenuSource, /TextOutline/)
  assert.doesNotMatch(nodeMenuSource, /ImageOutline/)
  assert.doesNotMatch(nodeMenuSource, /VideocamOutline/)
  assert.match(nodeMenuSource, /<CanvasSurface\s+v-if="show"/)
  assert.match(nodeMenuSource, /<CanvasNodeMenuHeader\s+v-if="mode !== 'connect'"/)
  assert.match(nodeMenuSource, /<CanvasNodeTypeList\s+:node-types="nodeTypes"/)
  assert.match(nodeMenuSource, /@select-node-type="\$emit\('selectNodeType', \$event\)"/)
  assert.match(nodeMenuSource, /<CanvasNodeMenuQuantity\s+:count="count"/)
  assert.match(nodeMenuSource, /@decrease-count="\$emit\('decreaseCount'\)"/)
  assert.match(nodeMenuSource, /@increase-count="\$emit\('increaseCount'\)"/)
  assert.doesNotMatch(nodeMenuSource, /v-for="nodeType in nodeTypes"/)
  assert.doesNotMatch(nodeMenuSource, /\.node-menu-header\s*\{/)
  assert.doesNotMatch(nodeMenuSource, /\.node-menu-stepper-value\s*\{/)

  assert.match(nodeMenuHeaderSource, /class="node-menu-header"/)
  assert.match(nodeMenuHeaderSource, /\{\{ title \}\}/)
  assert.match(nodeMenuHeaderSource, /\{\{ copy \}\}/)
  assert.match(nodeMenuHeaderSource, /\.node-menu-header\s*\{/)

  assert.match(nodeTypeListSource, /import \{ NIcon \} from 'naive-ui'/)
  assert.match(nodeTypeListSource, /TextOutline/)
  assert.match(nodeTypeListSource, /ImageOutline/)
  assert.match(nodeTypeListSource, /VideocamOutline/)
  assert.match(nodeTypeListSource, /v-for="nodeType in nodeTypes"/)
  assert.match(nodeTypeListSource, /@click="\$emit\('selectNodeType', nodeType\.type\)"/)
  assert.match(nodeTypeListSource, /\.node-menu-list\s*\{/)
  assert.match(nodeTypeListSource, /\.node-menu-item-description\s*\{/)

  assert.match(nodeMenuQuantitySource, /defineEmits\(\['decreaseCount', 'increaseCount'\]\)/)
  assert.match(nodeMenuQuantitySource, /:disabled="count <= 1"/)
  assert.match(nodeMenuQuantitySource, /:disabled="count >= 5"/)
  assert.match(nodeMenuQuantitySource, /@click="\$emit\('decreaseCount'\)"/)
  assert.match(nodeMenuQuantitySource, /@click="\$emit\('increaseCount'\)"/)
  assert.match(nodeMenuQuantitySource, /\.node-menu-quantity\s*\{/)
  assert.match(nodeMenuQuantitySource, /\.node-menu-stepper-value\s*\{/)
})

test('canvas view delegates sync resolution modals to a focused component', () => {
  const syncModalsSource = readComponentSource('CanvasSyncModals')
  const syncConflictModalSource = readComponentSource('CanvasSyncConflictModal')
  const remoteRefreshModalSource = readComponentSource('CanvasRemoteRefreshModal')

  assert.match(canvasSource, /import CanvasSyncModals from '@\/components\/canvas\/CanvasSyncModals\.vue'/)
  assert.match(canvasSource, /import \{ useCanvasSyncResolution \} from '@\/hooks\/useCanvasSyncResolution\.js'/)
  assert.match(canvasSource, /useCanvasSyncResolution\(\{/)
  const projectIdDeclarationIndex = canvasSource.indexOf('const currentCanvasProjectId = computed(() =>')
  const syncResolutionIndex = canvasSource.indexOf('useCanvasSyncResolution({')
  assert.ok(projectIdDeclarationIndex >= 0)
  assert.ok(syncResolutionIndex >= 0)
  assert.ok(
    projectIdDeclarationIndex < syncResolutionIndex,
    'currentCanvasProjectId must be declared before sync resolution setup'
  )
  assert.equal([...canvasSource.matchAll(/<CanvasSyncModals\b/g)].length, 1)
  assert.match(canvasSource, /v-model:show-conflict="showConflictModal"/)
  assert.match(canvasSource, /v-model:show-remote-refresh="showRemoteRefreshModal"/)
  assert.match(canvasSource, /:conflict-action="conflictAction"/)
  assert.match(canvasSource, /:remote-refresh-action="remoteRefreshAction"/)
  assert.match(canvasSource, /@cancel-conflict="cancelConflictResolution"/)
  assert.match(canvasSource, /@save-conflict-copy="saveConflictAsCopy"/)
  assert.match(canvasSource, /@refresh-conflict="refreshRemoteConflict"/)
  assert.match(canvasSource, /@overwrite-conflict="overwriteRemoteConflict"/)
  assert.match(canvasSource, /@confirm-remote-refresh="confirmRemoteRefresh"/)
  assert.doesNotMatch(canvasSource, /const syncIndicator = computed\(\(\) =>/)
  assert.doesNotMatch(canvasSource, /const refreshRemoteConflict = async \(\) =>/)
  assert.doesNotMatch(canvasSource, /const overwriteRemoteConflict = async \(\) =>/)
  assert.doesNotMatch(canvasSource, /const confirmRemoteRefresh = async \(\) =>/)
  assert.doesNotMatch(canvasSource, /const saveConflictAsCopy = async \(\) =>/)
  assert.doesNotMatch(canvasSource, /title="Sync conflict"/)
  assert.doesNotMatch(canvasSource, /title="Refresh from cloud"/)
  assert.doesNotMatch(canvasSource, /class="conflict-actions"/)

  assert.match(syncModalsSource, /import CanvasSyncConflictModal from '\.\/CanvasSyncConflictModal\.vue'/)
  assert.match(syncModalsSource, /import CanvasRemoteRefreshModal from '\.\/CanvasRemoteRefreshModal\.vue'/)
  assert.match(syncModalsSource, /defineEmits\(\[\s*'update:showConflict'/s)
  assert.match(syncModalsSource, /<CanvasSyncConflictModal\s+:show="showConflict"/)
  assert.match(syncModalsSource, /@update:show="\$emit\('update:showConflict', \$event\)"/)
  assert.match(syncModalsSource, /@save-copy="\$emit\('saveConflictCopy'\)"/)
  assert.match(syncModalsSource, /@overwrite="\$emit\('overwriteConflict'\)"/)
  assert.match(syncModalsSource, /<CanvasRemoteRefreshModal\s+:show="showRemoteRefresh"/)
  assert.match(syncModalsSource, /@update:show="\$emit\('update:showRemoteRefresh', \$event\)"/)
  assert.match(syncModalsSource, /@confirm="\$emit\('confirmRemoteRefresh'\)"/)
  assert.doesNotMatch(syncModalsSource, /import \{ BaseButton, BaseModal, BaseModalActions, BaseModalCopy \} from '@\/components\/ui'/)
  assert.doesNotMatch(syncModalsSource, /title="Sync conflict"/)
  assert.doesNotMatch(syncModalsSource, /title="Refresh from cloud"/)
  assert.doesNotMatch(syncModalsSource, /\.conflict-actions\s*\{/)

  assert.match(syncConflictModalSource, /import \{ BaseButton, BaseModal, BaseModalActions, BaseModalCopy \} from '@\/components\/ui'/)
  assert.match(syncConflictModalSource, /title="Sync conflict"/)
  assert.match(syncConflictModalSource, /:close-on-overlay="false"/)
  assert.match(syncConflictModalSource, /:loading="action === 'copy'"/)
  assert.match(syncConflictModalSource, /:disabled="!!action && action !== 'copy'"/)
  assert.match(syncConflictModalSource, /@click="\$emit\('saveCopy'\)"/)
  assert.match(syncConflictModalSource, /@click="\$emit\('refresh'\)"/)
  assert.match(syncConflictModalSource, /@click="\$emit\('overwrite'\)"/)
  assert.match(syncConflictModalSource, /\.conflict-actions\s*\{/)
  assert.match(syncConflictModalSource, /:deep\(\.ui-button-text\)/)

  assert.match(remoteRefreshModalSource, /import \{ BaseButton, BaseModal, BaseModalActions, BaseModalCopy \} from '@\/components\/ui'/)
  assert.match(remoteRefreshModalSource, /title="Load cloud version"/)
  assert.match(remoteRefreshModalSource, /:close-on-overlay="action !== 'refresh'"/)
  assert.match(remoteRefreshModalSource, /@click="\$emit\('update:show', false\)"/)
  assert.match(remoteRefreshModalSource, /@click="\$emit\('confirm'\)"/)
})

test('canvas view delegates route lifecycle orchestration to a focused composable', () => {
  const routeLifecycleSource = readHookSource('useCanvasRouteLifecycle')

  assert.match(canvasSource, /import \{ useCanvasRouteLifecycle \} from '@\/hooks\/useCanvasRouteLifecycle\.js'/)
  assert.match(canvasSource, /useCanvasRouteLifecycle\(\{/)
  assert.match(canvasSource, /loadProjectById: \(projectId\) => loadProjectById\(projectId\)/)
  assert.doesNotMatch(canvasSource, /const checkMobile = \(\) =>/)
  assert.doesNotMatch(canvasSource, /const recoverBlankMediaNodes = async \(projectId\) =>/)
  assert.doesNotMatch(canvasSource, /const ensureProjectSnapshot = async \(projectId\) =>/)
  assert.doesNotMatch(canvasSource, /const applyPendingWorkflowTemplate = async \(\) =>/)
  assert.doesNotMatch(canvasSource, /watch\(\s*\(\) => route\.params\.id,/)
  assert.doesNotMatch(canvasSource, /onMounted\(async \(\) => \{/)
  assert.doesNotMatch(canvasSource, /onUnmounted\(\(\) => \{/)

  assert.match(routeLifecycleSource, /import \{ nextTick, onMounted, onUnmounted, watch \} from 'vue'/)
  assert.match(routeLifecycleSource, /export const useCanvasRouteLifecycle = \(/)
  assert.match(routeLifecycleSource, /watchFn\(\s*\(\) => route\.params\.id,/)
  assert.match(routeLifecycleSource, /onMountedFn\(async \(\) => \{/)
  assert.match(routeLifecycleSource, /onUnmountedFn\(\(\) => \{/)
  assert.match(routeLifecycleSource, /recoverMissingNodeMediaFn\(\{/)
  assert.match(routeLifecycleSource, /shouldUseCachedProjectBeforeRemoteFn\(\{/)
  assert.match(routeLifecycleSource, /shouldApplyRemoteProjectSnapshotFn\(\{/)
})

test('canvas view delegates project and group modals to a focused component', () => {
  const projectModalsSource = readComponentSource('CanvasProjectModals')
  const projectRenameModalSource = readComponentSource('CanvasProjectRenameModal')
  const projectDeleteModalSource = readComponentSource('CanvasProjectDeleteModal')
  const groupRenameModalSource = readComponentSource('CanvasGroupRenameModal')
  const projectActionsSource = readHookSource('useCanvasProjectActions')
  const projectUiStateSource = readHookSource('useCanvasProjectUiState')

  assert.match(canvasSource, /import CanvasProjectModals from '@\/components\/canvas\/CanvasProjectModals\.vue'/)
  assert.equal([...canvasSource.matchAll(/<CanvasProjectModals\b/g)].length, 1)
  assert.match(canvasSource, /v-model:show-rename="showRenameModal"/)
  assert.match(canvasSource, /v-model:show-delete="showDeleteModal"/)
  assert.match(canvasSource, /v-model:show-group-rename="showGroupRenameModal"/)
  assert.match(canvasSource, /v-model:rename-value="renameValue"/)
  assert.match(canvasSource, /v-model:group-rename-value="groupRenameValue"/)
  assert.match(canvasSource, /:project-name="projectName"/)
  assert.match(canvasSource, /@confirm-rename="confirmRename"/)
  assert.match(canvasSource, /@confirm-delete="confirmDelete"/)
  assert.match(canvasSource, /@confirm-rename-group="confirmRenameGroup"/)
  assert.doesNotMatch(canvasSource, /title="Rename project"/)
  assert.doesNotMatch(canvasSource, /title="Delete project"/)
  assert.doesNotMatch(canvasSource, /title="Rename group"/)
  assert.doesNotMatch(canvasSource, /Delete "\{\{ projectName \}\}"/)

  assert.match(projectModalsSource, /import CanvasProjectRenameModal from '\.\/CanvasProjectRenameModal\.vue'/)
  assert.match(projectModalsSource, /import CanvasProjectDeleteModal from '\.\/CanvasProjectDeleteModal\.vue'/)
  assert.match(projectModalsSource, /import CanvasGroupRenameModal from '\.\/CanvasGroupRenameModal\.vue'/)
  assert.match(projectModalsSource, /defineEmits\(\[\s*'update:showRename'/s)
  assert.match(projectModalsSource, /<CanvasProjectRenameModal\s+:show="showRename"/)
  assert.match(projectModalsSource, /@update:show="\$emit\('update:showRename', \$event\)"/)
  assert.match(projectModalsSource, /@update:value="\$emit\('update:renameValue', \$event\)"/)
  assert.match(projectModalsSource, /@confirm="\$emit\('confirmRename'\)"/)
  assert.match(projectModalsSource, /<CanvasProjectDeleteModal\s+:show="showDelete"/)
  assert.match(projectModalsSource, /@update:show="\$emit\('update:showDelete', \$event\)"/)
  assert.match(projectModalsSource, /@confirm="\$emit\('confirmDelete'\)"/)
  assert.match(projectModalsSource, /<CanvasGroupRenameModal\s+:show="showGroupRename"/)
  assert.match(projectModalsSource, /@update:show="\$emit\('update:showGroupRename', \$event\)"/)
  assert.match(projectModalsSource, /@update:value="\$emit\('update:groupRenameValue', \$event\)"/)
  assert.match(projectModalsSource, /@confirm="\$emit\('confirmRenameGroup'\)"/)
  assert.doesNotMatch(projectModalsSource, /import \{ BaseButton, BaseInput, BaseModal, BaseModalActions, BaseModalCopy \} from '@\/components\/ui'/)
  assert.doesNotMatch(projectModalsSource, /title="Rename project"/)
  assert.doesNotMatch(projectModalsSource, /title="Delete project"/)
  assert.doesNotMatch(projectModalsSource, /title="Rename group"/)
  assert.doesNotMatch(projectModalsSource, /Delete "\{\{ projectName \}\}"/)

  assert.match(projectRenameModalSource, /import \{ BaseButton, BaseInput, BaseModal, BaseModalActions \} from '@\/components\/ui'/)
  assert.match(projectRenameModalSource, /title="Rename project"/)
  assert.match(projectRenameModalSource, /:model-value="value"/)
  assert.match(projectRenameModalSource, /@update:model-value="\$emit\('update:value', \$event\)"/)
  assert.match(projectRenameModalSource, /@click="\$emit\('confirm'\)"/)

  assert.match(projectDeleteModalSource, /import \{ BaseButton, BaseModal, BaseModalActions, BaseModalCopy \} from '@\/components\/ui'/)
  assert.match(projectDeleteModalSource, /title="Delete project"/)
  assert.match(projectDeleteModalSource, /Delete "\{\{ projectName \}\}"/)
  assert.match(projectDeleteModalSource, /@click="\$emit\('confirm'\)"/)

  assert.match(groupRenameModalSource, /import \{ BaseButton, BaseInput, BaseModal, BaseModalActions \} from '@\/components\/ui'/)
  assert.match(groupRenameModalSource, /title="Rename group"/)
  assert.match(groupRenameModalSource, /:model-value="value"/)
  assert.match(groupRenameModalSource, /@update:model-value="\$emit\('update:value', \$event\)"/)
  assert.match(groupRenameModalSource, /@keyup\.enter="\$emit\('confirm'\)"/)

  assert.match(projectActionsSource, /import \{ useCanvasProjectUiState \} from '\.\/useCanvasProjectUiState\.js'/)
  assert.match(projectActionsSource, /useCanvasProjectUiState\(\{\s*route,\s*projects,\s*currentWorkspace\s*\}\)/)
  assert.ok(
    projectActionsSource.indexOf('...uiState') < projectActionsSource.indexOf('openShareDialog,'),
    'business project actions should override UI-only state helpers with the same names'
  )
  assert.doesNotMatch(projectActionsSource, /const showRenameModal = ref\(false\)/)
  assert.doesNotMatch(projectActionsSource, /const showDeleteModal = ref\(false\)/)
  assert.doesNotMatch(projectActionsSource, /const showShareModal = ref\(false\)/)
  assert.doesNotMatch(projectActionsSource, /const projectOptions = \[/)
  assert.match(projectUiStateSource, /export const useCanvasProjectUiState = \(/)
  assert.match(projectUiStateSource, /const showRenameModal = ref\(false\)/)
  assert.match(projectUiStateSource, /const showDeleteModal = ref\(false\)/)
  assert.match(projectUiStateSource, /const showShareModal = ref\(false\)/)
  assert.match(projectUiStateSource, /export const canvasProjectOptions = Object\.freeze/)
})

test('canvas view delegates auxiliary panels to a focused component', () => {
  const auxiliaryPanelsSource = readComponentSource('CanvasAuxiliaryPanels')

  assert.match(canvasSource, /import CanvasAuxiliaryPanels from '@\/components\/canvas\/CanvasAuxiliaryPanels\.vue'/)
  assert.equal([...canvasSource.matchAll(/<CanvasAuxiliaryPanels\b/g)].length, 1)
  assert.match(canvasSource, /v-model:show-api-settings="showApiSettings"/)
  assert.match(canvasSource, /v-model:show-media-library="showMediaLibraryPanel"/)
  assert.match(canvasSource, /:project-id="currentCanvasProjectId"/)
  assert.match(canvasSource, /@insert-asset="handleInsertLibraryAsset"/)
  assert.doesNotMatch(canvasSource, /import ApiSettings from '@\/components\/ApiSettings\.vue'/)
  assert.doesNotMatch(canvasSource, /import MediaLibraryPanel from '@\/components\/MediaLibraryPanel\.vue'/)
  assert.doesNotMatch(canvasSource, /<ApiSettings\b/)
  assert.doesNotMatch(canvasSource, /<MediaLibraryPanel\b/)

  assert.match(auxiliaryPanelsSource, /import ApiSettings from '@\/components\/ApiSettings\.vue'/)
  assert.match(auxiliaryPanelsSource, /import MediaLibraryPanel from '@\/components\/MediaLibraryPanel\.vue'/)
  assert.match(auxiliaryPanelsSource, /<ApiSettings/)
  assert.match(auxiliaryPanelsSource, /<MediaLibraryPanel/)
  assert.match(auxiliaryPanelsSource, /:show="showApiSettings"/)
  assert.match(auxiliaryPanelsSource, /@update:show="\$emit\('update:showApiSettings', \$event\)"/)
  assert.match(auxiliaryPanelsSource, /:show="showMediaLibrary"/)
  assert.match(auxiliaryPanelsSource, /:project-id="projectId"/)
  assert.match(auxiliaryPanelsSource, /@insert-asset="\$emit\('insertAsset', \$event\)"/)
})

test('canvas view delegates workspace share modal to a focused component', () => {
  const shareModalSource = readComponentSource('CanvasShareModal')
  const shareSectionSource = readComponentSource('CanvasShareSection')
  const shareWorkspaceSource = readComponentSource('CanvasShareWorkspaceSection')
  const shareTemplateFormSource = readComponentSource('CanvasShareTemplateForm')
  const shareStatusSource = readComponentSource('CanvasShareStatusSection')
  const shareActionsSource = readComponentSource('CanvasShareActions')

  assert.match(canvasSource, /import CanvasShareModal from '@\/components\/canvas\/CanvasShareModal\.vue'/)
  assert.equal([...canvasSource.matchAll(/<CanvasShareModal\b/g)].length, 1)
  assert.match(canvasSource, /v-model:show="showShareModal"/)
  assert.match(canvasSource, /v-model:template-name="shareTemplateName"/)
  assert.match(canvasSource, /v-model:template-description="shareTemplateDescription"/)
  assert.match(canvasSource, /:workspace-name="workspaceName"/)
  assert.match(canvasSource, /:status-loading="shareDialogLoading"/)
  assert.match(canvasSource, /:published="isTemplatePublished"/)
  assert.match(canvasSource, /:last-published-at="lastPublishedAt"/)
  assert.match(canvasSource, /:action-loading="shareActionLoading"/)
  assert.match(canvasSource, /@close="showShareModal = false"/)
  assert.match(canvasSource, /@unpublish="removeSharedTemplate"/)
  assert.match(canvasSource, /@save="saveSharedTemplate"/)
  assert.doesNotMatch(canvasSource, /title="Share To Workspace"/)
  assert.doesNotMatch(canvasSource, /class="share-panel"/)
  assert.doesNotMatch(canvasSource, /class="share-textarea/)

  assert.match(shareModalSource, /import \{ BaseModal \} from '@\/components\/ui'/)
  assert.match(shareModalSource, /import CanvasShareActions from '\.\/CanvasShareActions\.vue'/)
  assert.match(shareModalSource, /import CanvasShareStatusSection from '\.\/CanvasShareStatusSection\.vue'/)
  assert.match(shareModalSource, /import CanvasShareTemplateForm from '\.\/CanvasShareTemplateForm\.vue'/)
  assert.match(shareModalSource, /import CanvasShareWorkspaceSection from '\.\/CanvasShareWorkspaceSection\.vue'/)
  assert.match(shareModalSource, /defineEmits\(\[\s*'update:show'/s)
  assert.match(shareModalSource, /title="Share To Workspace"/)
  assert.match(shareModalSource, /class="share-panel"/)
  assert.match(shareModalSource, /<CanvasShareWorkspaceSection\s+:workspace-name="workspaceName"/)
  assert.match(shareModalSource, /<CanvasShareTemplateForm\s+:template-name="templateName"/)
  assert.match(shareModalSource, /@update:template-name="\$emit\('update:templateName', \$event\)"/)
  assert.match(shareModalSource, /@update:template-description="\$emit\('update:templateDescription', \$event\)"/)
  assert.match(shareModalSource, /<CanvasShareStatusSection\s+:status-loading="statusLoading"/)
  assert.match(shareModalSource, /<CanvasShareActions\s+:published="published"/)
  assert.match(shareModalSource, /@close="\$emit\('close'\)"/)
  assert.match(shareModalSource, /@unpublish="\$emit\('unpublish'\)"/)
  assert.match(shareModalSource, /@save="\$emit\('save'\)"/)
  assert.match(shareModalSource, /\.share-panel\s*\{/)
  assert.doesNotMatch(shareModalSource, /import \{ BaseButton, BaseInput, BaseModal, BaseModalActions \} from '@\/components\/ui'/)
  assert.doesNotMatch(shareModalSource, /class="share-textarea/)
  assert.doesNotMatch(shareModalSource, /Published to Featured Templates/)
  assert.doesNotMatch(shareModalSource, /\{\{ published \? 'Update Template' : 'Publish Template' \}\}/)

  assert.match(shareSectionSource, /class="share-section"/)
  assert.match(shareSectionSource, /class="share-heading"/)
  assert.match(shareSectionSource, /<slot/)
  assert.match(shareSectionSource, /\.share-section\s*\{/)
  assert.match(shareSectionSource, /\.share-heading p\s*\{/)

  assert.match(shareWorkspaceSource, /import CanvasShareSection from '\.\/CanvasShareSection\.vue'/)
  assert.match(shareWorkspaceSource, /title="Workspace"/)
  assert.match(shareWorkspaceSource, /\{\{ workspaceName \}\}/)

  assert.match(shareTemplateFormSource, /import \{ BaseInput \} from '@\/components\/ui'/)
  assert.match(shareTemplateFormSource, /import CanvasShareSection from '\.\/CanvasShareSection\.vue'/)
  assert.match(shareTemplateFormSource, /title="Template Details"/)
  assert.match(shareTemplateFormSource, /:model-value="templateName"/)
  assert.match(shareTemplateFormSource, /@update:model-value="\$emit\('update:templateName', \$event\)"/)
  assert.match(shareTemplateFormSource, /:value="templateDescription"/)
  assert.match(shareTemplateFormSource, /@input="\$emit\('update:templateDescription', \$event\.target\.value\)"/)
  assert.match(shareTemplateFormSource, /\.share-textarea:focus\s*\{/)

  assert.match(shareStatusSource, /import CanvasShareSection from '\.\/CanvasShareSection\.vue'/)
  assert.match(shareStatusSource, /title="Status"/)
  assert.match(shareStatusSource, /v-if="statusLoading"/)
  assert.match(shareStatusSource, /Published to Featured Templates/)
  assert.match(shareStatusSource, /new Date\(lastPublishedAt\)\.toLocaleString\(\)/)

  assert.match(shareActionsSource, /import \{ BaseButton, BaseModalActions \} from '@\/components\/ui'/)
  assert.match(shareActionsSource, /v-if="published"/)
  assert.match(shareActionsSource, /:loading="actionLoading \|\| statusLoading"/)
  assert.match(shareActionsSource, /\{\{ published \? 'Update Template' : 'Publish Template' \}\}/)
  assert.match(shareActionsSource, /@click="\$emit\('close'\)"/)
  assert.match(shareActionsSource, /@click="\$emit\('unpublish'\)"/)
  assert.match(shareActionsSource, /@click="\$emit\('save'\)"/)
})
