import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { test } from 'node:test'

const workspaceSource = readFileSync(new URL('./Workspace.vue', import.meta.url), 'utf8')
const styleSource = readFileSync(new URL('../style.css', import.meta.url), 'utf8')
const iconsSource = readFileSync(new URL('../icons/coolicons.js', import.meta.url), 'utf8')
const projectsStoreSource = readFileSync(new URL('../stores/projects.js', import.meta.url), 'utf8')

function readWorkspaceComponentSource(name) {
  const path = fileURLToPath(new URL(`../components/workspace/${name}.vue`, import.meta.url))
  return existsSync(path) ? readFileSync(path, 'utf8') : ''
}

function readWorkspaceUtilsSource(name) {
  const path = fileURLToPath(new URL(`../utils/${name}.js`, import.meta.url))
  return existsSync(path) ? readFileSync(path, 'utf8') : ''
}

test('workspace view delegates the main header to a focused component', () => {
  const headerSource = readWorkspaceComponentSource('WorkspaceHeader')
  const actionPillSource = readWorkspaceComponentSource('WorkspaceActionPill')

  assert.match(workspaceSource, /import WorkspaceHeader from '@\/components\/workspace\/WorkspaceHeader\.vue'/)
  assert.equal([...workspaceSource.matchAll(/<WorkspaceHeader\b/g)].length, 1)
  assert.match(workspaceSource, /:title="sectionTitle"/)
  assert.match(workspaceSource, /:description="sectionDescription"/)
  assert.match(workspaceSource, /@back-home="router\.push\('\/'\)"/)
  assert.match(workspaceSource, /@create-project="createBlankProject"/)
  assert.doesNotMatch(workspaceSource, /import WorkspaceActionPill/)
  assert.doesNotMatch(workspaceSource, /<WorkspaceActionPill[\s>]/)
  assert.doesNotMatch(workspaceSource, /<header class="main-header"/)
  assert.doesNotMatch(workspaceSource, /\.main-header\s*\{/)
  assert.doesNotMatch(workspaceSource, /\.header-actions\s*\{/)
  assert.doesNotMatch(workspaceSource, /ui-action-pill/)
  assert.doesNotMatch(styleSource, /\.ui-action-pill(?:\s|\.|:|\{)/)

  assert.match(headerSource, /import WorkspaceActionPill from '\.\/WorkspaceActionPill\.vue'/)
  assert.match(headerSource, /<header class="main-header">/)
  assert.match(headerSource, /<div class="main-header-copy">/)
  assert.match(headerSource, /\{\{ title \}\}/)
  assert.match(headerSource, /\{\{ description \}\}/)
  assert.match(headerSource, /@click="\$emit\('backHome'\)"/)
  assert.match(headerSource, /@click="\$emit\('createProject'\)"/)
  assert.match(headerSource, /<NIcon :size="15"><GridOutline \/><\/NIcon>/)
  assert.match(headerSource, /<NIcon :size="15"><AddOutline \/><\/NIcon>/)
  assert.match(headerSource, /<WorkspaceActionPill\s+variant="primary"\s+@click="\$emit\('createProject'\)"/)
  assert.match(headerSource, /defineEmits\(\['backHome', 'createProject'\]\)/)
  assert.match(headerSource, /\.main-header\s*\{/)
  assert.match(headerSource, /\.main-header\s*\{[^}]*align-items:\s*flex-start/s)
  assert.match(headerSource, /\.header-actions\s*\{/)
  assert.match(headerSource, /\.header-actions\s*\{[^}]*gap:\s*8px/s)
  assert.match(headerSource, /\.header-actions\s*\{[^}]*align-self:\s*flex-start/s)
  assert.match(actionPillSource, /'workspace-action-pill'/)
  assert.match(actionPillSource, /class="workspace-action-pill-label"/)
  assert.match(actionPillSource, /variant:\s*\{[\s\S]*default:\s*'default'/)
  assert.match(actionPillSource, /`workspace-action-pill--\$\{props\.variant\}`/)
  assert.match(actionPillSource, /\.workspace-action-pill--primary\s*\{[^}]*background:\s*#fff/s)
  assert.match(actionPillSource, /\.workspace-action-pill--primary\s*\{[^}]*color:\s*#0d0e10/s)
  assert.match(actionPillSource, /defineEmits\(\['click'\]\)/)
  assert.match(actionPillSource, /\.workspace-action-pill\s*\{[^}]*display:\s*inline-flex/s)
  assert.match(actionPillSource, /\.workspace-action-pill\s*\{[^}]*gap:\s*8px/s)
  assert.match(actionPillSource, /\.workspace-action-pill\s*\{[^}]*height:\s*38px/s)
  assert.match(actionPillSource, /\.workspace-action-pill\s*\{[^}]*width:\s*128px/s)
  assert.match(actionPillSource, /\.workspace-action-pill\s*\{[^}]*padding:\s*0 14px/s)
  assert.match(actionPillSource, /\.workspace-action-pill-label\s*\{[^}]*font-size:\s*13px/s)
  assert.match(actionPillSource, /\.workspace-action-pill-label\s*\{[^}]*white-space:\s*nowrap/s)
})

test('workspace shared templates header uses compact title and description spacing', () => {
  const headerSource = readWorkspaceComponentSource('WorkspaceHeader')
  const cardsGridSource = readWorkspaceComponentSource('WorkspaceCardsGrid')

  assert.match(headerSource, /\.main-header-copy\s*\{[^}]*flex:\s*1 1 auto/s)
  assert.match(headerSource, /\.main-header-copy\s*\{[^}]*min-width:\s*0/s)
  assert.match(headerSource, /\.main-header h1\s*\{[^}]*font-size:\s*20px/s)
  assert.match(headerSource, /\.main-header p\s*\{[^}]*margin:\s*0;/s)
  assert.match(headerSource, /\.main-header p\s*\{[^}]*font-size:\s*13px/s)
  assert.match(headerSource, /\.main-header p\s*\{[^}]*line-height:\s*1\.55/s)
  assert.match(headerSource, /\.main-header p\s*\{[^}]*max-width:\s*min\(760px,\s*100%\)/s)
  assert.match(headerSource, /\.main-header p\s*\{[^}]*white-space:\s*nowrap/s)
  assert.match(headerSource, /\.main-header p\s*\{[^}]*text-overflow:\s*ellipsis/s)
  assert.match(headerSource, /@media \(max-width:\s*720px\)/)
  assert.match(headerSource, /@media \(max-width:\s*720px\)[\s\S]*\.main-header p\s*\{[^}]*white-space:\s*normal/s)
  assert.doesNotMatch(headerSource, /\.main-header p\s*\{[^}]*margin:\s*10px 0 0/s)
  assert.doesNotMatch(cardsGridSource, /\.cards-empty-state\s*\{[^}]*border-top/s)
})

test('workspace view delegates sidebar navigation and account chrome to a focused component', () => {
  const sidebarSource = readWorkspaceComponentSource('WorkspaceSidebar')

  assert.match(workspaceSource, /import WorkspaceSidebar from '@\/components\/workspace\/WorkspaceSidebar\.vue'/)
  assert.equal([...workspaceSource.matchAll(/<WorkspaceSidebar\b/g)].length, 1)
  assert.match(workspaceSource, /v-model:active-section="activeSection"/)
  assert.match(workspaceSource, /:workspace-brand="workspaceBrand"/)
  assert.match(workspaceSource, /:nav-items="navItems"/)
  assert.match(workspaceSource, /:is-authenticated="isAuthenticated"/)
  assert.match(workspaceSource, /:user="user"/)
  assert.match(workspaceSource, /:avatar-initial="avatarInitial"/)
  assert.match(workspaceSource, /@upload-avatar="triggerAvatarUpload"/)
  assert.match(workspaceSource, /@logout="handleLogout"/)
  assert.doesNotMatch(workspaceSource, /<aside class="workspace-sidebar"/)
  assert.doesNotMatch(workspaceSource, /\.workspace-sidebar\s*\{/)
  assert.doesNotMatch(workspaceSource, /\.sidebar-account\s*\{/)
  assert.doesNotMatch(workspaceSource, /\.account-action-btn\s*\{/)

  assert.match(sidebarSource, /<aside class="workspace-sidebar">/)
  assert.doesNotMatch(sidebarSource, /aioncraftWordmark/)
  assert.doesNotMatch(sidebarSource, /home-figma\/aioncraft-wordmark/)
  assert.doesNotMatch(sidebarSource, /class="brand"/)
  assert.doesNotMatch(sidebarSource, /brand-logo/)
  assert.doesNotMatch(sidebarSource, /\.brand\s*\{/)
  assert.doesNotMatch(sidebarSource, /\.brand-logo\s*\{/)
  assert.doesNotMatch(sidebarSource, /brand-divider/)
  assert.doesNotMatch(sidebarSource, /brand-text/)
  assert.doesNotMatch(sidebarSource, /src="\/project-logo\.svg"/)
  assert.match(sidebarSource, /v-for="item in navItems"/)
  assert.match(sidebarSource, /:class="\{ active: activeSection === item\.key \}"/)
  assert.match(sidebarSource, /@click="\$emit\('update:activeSection', item\.key\)"/)
  assert.match(sidebarSource, /<NIcon class="nav-icon" :size="18"><component :is="item\.icon" \/><\/NIcon>/)
  assert.doesNotMatch(sidebarSource, /sidebar-group-title/)
  assert.doesNotMatch(sidebarSource, />Workspace<\/div>/)
  assert.doesNotMatch(sidebarSource, /class="sidebar-group private-group"/)
  assert.doesNotMatch(sidebarSource, /<div class="sidebar-group-title">Private<\/div>/)
  assert.doesNotMatch(sidebarSource, /class="nav-item private-nav-item"/)
  assert.doesNotMatch(sidebarSource, /All Private/)
  assert.match(sidebarSource, /class="sidebar-footer-tools"/)
  assert.doesNotMatch(sidebarSource, /class="usage-pill"/)
  assert.doesNotMatch(sidebarSource, /0% used/)
  assert.doesNotMatch(sidebarSource, /title="Trash"/)
  assert.match(sidebarSource, /title="Profile settings"/)
  assert.match(sidebarSource, /class="sidebar-profile-btn"/)
  assert.match(sidebarSource, /:fallback-name="workspaceBrand"/)
  assert.match(sidebarSource, /user\?\.avatarUrl/)
  assert.match(sidebarSource, /\{\{ avatarInitial \}\}/)
  assert.match(sidebarSource, /title="Admin Dashboard"/)
  assert.match(sidebarSource, /title="Logout"/)
  assert.match(sidebarSource, /class="sidebar-tool-btn sidebar-tool-btn--logout"/)
  assert.doesNotMatch(sidebarSource, /title="Help"/)
  assert.doesNotMatch(sidebarSource, /TrashOutline/)
  assert.doesNotMatch(sidebarSource, /SettingsOutline/)
  assert.doesNotMatch(sidebarSource, /DashboardOutline/)
  assert.match(sidebarSource, /WindowSidebarOutline/)
  assert.match(sidebarSource, /LogOutOutline/)
  assert.doesNotMatch(sidebarSource, /HelpCircleOutline/)
  assert.doesNotMatch(sidebarSource, /@click="\$emit\('usage'\)"/)
  assert.match(sidebarSource, /@click="\$emit\('settings'\)"/)
  assert.match(sidebarSource, /@click="\$emit\('admin'\)"/)
  assert.match(sidebarSource, /@click="\$emit\('logout'\)"/)
  assert.match(sidebarSource, /@click="\$emit\('login'\)"/)
  assert.match(sidebarSource, /@click="\$emit\('register'\)"/)
  assert.doesNotMatch(sidebarSource, /account-compact/)
  assert.doesNotMatch(sidebarSource, /account-icon-button/)
  assert.doesNotMatch(sidebarSource, /account-user-button/)
  assert.doesNotMatch(sidebarSource, /class="account-profile"/)
  assert.doesNotMatch(sidebarSource, /class="account-meta"/)
  assert.match(sidebarSource, /defineEmits\(\[\s*'update:activeSection'/s)
  assert.match(sidebarSource, /\.workspace-sidebar\s*\{/)
  assert.match(sidebarSource, /\.sidebar-footer-tools\s*\{/)
  assert.doesNotMatch(sidebarSource, /\.usage-pill\s*\{/)
  assert.match(sidebarSource, /\.sidebar-footer-tools\s*\{[^}]*justify-content:\s*flex-start/s)
  assert.match(sidebarSource, /\.sidebar-tool-actions\s*\{[^}]*gap:\s*10px/s)
  assert.match(sidebarSource, /\.sidebar-tool-actions\s*\{[^}]*width:\s*100%/s)
  assert.match(sidebarSource, /\.sidebar-tool-btn\s*\{[^}]*width:\s*26px/s)
  assert.match(sidebarSource, /\.sidebar-tool-btn\s*\{[^}]*height:\s*30px/s)
  assert.match(sidebarSource, /\.sidebar-tool-btn--logout\s*\{[^}]*margin-left:\s*auto/s)
  assert.match(sidebarSource, /\.sidebar-tool-btn:hover\s*\{/)
  assert.doesNotMatch(workspaceSource, /@usage="router\.push\('\/usage'\)"/)
  assert.doesNotMatch(workspaceSource, /@settings="router\.push\('\/usage'\)"/)
  assert.match(workspaceSource, /@settings="openProfileSettings"/)
  assert.match(workspaceSource, /<WorkspaceProfileModal/)
  assert.match(workspaceSource, /v-model:show="showProfileModal"/)
  assert.match(workspaceSource, /@upload-avatar="triggerAvatarUpload"/)
  assert.match(workspaceSource, /@save-profile="saveProfileSettings"/)
  assert.match(workspaceSource, /@admin="router\.push\('\/admin\/dashboard'\)"/)
  assert.match(workspaceSource, /PersonOutline/)
  assert.match(workspaceSource, /BookmarkOutline/)
  assert.match(workspaceSource, /\{ key: 'shared', label: 'Shared with me', icon: PersonOutline \}/)
  assert.match(workspaceSource, /\{ key: 'featured', label: 'Shared Template', icon: BookmarkOutline \}/)
  assert.doesNotMatch(workspaceSource, /label: 'Share Templates'/)
  assert.match(iconsSource, /export const PersonOutline = wrap\(userCircle\)/)
  assert.match(iconsSource, /export const BookmarkOutline = wrap\(bookmark\)/)
  assert.match(iconsSource, /export const WindowSidebarOutline = wrap\(windowSidebar\)/)
  assert.match(iconsSource, /export const LogOutOutline = wrap\(logOut\)/)
})

test('workspace switcher separates personal and team workspace lists', () => {
  const switcherSource = readWorkspaceComponentSource('WorkspaceSwitcher')

  assert.match(switcherSource, /placeholder="Search workspaces"/)
  assert.match(switcherSource, /<div class="switcher-label">Personal<\/div>/)
  assert.match(switcherSource, /<div class="switcher-label">Teams<\/div>/)
  assert.match(switcherSource, /const personalWorkspaces = computed/)
  assert.match(switcherSource, /const teamWorkspaces = computed/)
  assert.match(switcherSource, /const workspaceMatchesSearch = \(workspace\) => \{/)
  assert.match(switcherSource, /formatWorkspaceOptionMeta\(workspace\)/)
  assert.match(switcherSource, /No workspaces found/)
  assert.doesNotMatch(switcherSource, /ArrowDownUpOutline/)
  assert.match(switcherSource, /class="switcher-chevron-stack"/)
  assert.match(switcherSource, /<NIcon :size="9"><ChevronUpOutline \/><\/NIcon>/)
  assert.match(switcherSource, /<NIcon :size="9"><ChevronDownOutline \/><\/NIcon>/)
  assert.match(switcherSource, /\.switcher-chevron-stack\s*\{/)
  assert.match(switcherSource, /\.switcher-chevron-stack\s*\{[^}]*gap:\s*0/s)
  assert.match(switcherSource, /\.switcher-trigger\s*\{[^}]*background:\s*transparent/s)
  assert.match(switcherSource, /\.switcher-trigger\s*\{[^}]*border:\s*1px solid transparent/s)
  assert.match(switcherSource, /\.switcher-trigger:hover\s*\{[^}]*background:\s*rgba\(255,\s*255,\s*255,\s*0\.07\)/s)
  assert.match(switcherSource, /\.workspace-avatar\s*\{[^}]*border-radius:\s*999px/s)
  assert.match(switcherSource, /\.option-avatar\s*\{[^}]*border-radius:\s*999px/s)
})

test('workspace switcher exposes owner-only team edit and delete actions', () => {
  const switcherSource = readWorkspaceComponentSource('WorkspaceSwitcher')

  assert.match(switcherSource, /canManageWorkspace\(workspace\)/)
  assert.match(switcherSource, /const canManageCurrentWorkspace = computed/)
  assert.match(switcherSource, /class="workspace-edit-button"/)
  assert.match(switcherSource, /aria-label="Edit team"/)
  assert.match(switcherSource, /@click\.stop="editWorkspace\(workspace\)"/)
  assert.match(switcherSource, /emit\('edit', workspace\)/)
  assert.match(switcherSource, /v-if="canManageCurrentWorkspace"/)
  assert.match(switcherSource, />Delete team<\/span>/)
  assert.match(switcherSource, /emitAction\('delete'\)/)
  assert.match(switcherSource, /v-else-if="currentWorkspace\?\.kind === 'team'"/)
  assert.match(switcherSource, />Leave team<\/span>/)
})

test('workspace view delegates project and template cards to a focused component', () => {
  const cardsGridSource = readWorkspaceComponentSource('WorkspaceCardsGrid')

  assert.match(workspaceSource, /import WorkspaceCardsGrid from '@\/components\/workspace\/WorkspaceCardsGrid\.vue'/)
  assert.equal([...workspaceSource.matchAll(/<WorkspaceCardsGrid\b/g)].length, 1)
  assert.match(workspaceSource, /:active-section="activeSection"/)
  assert.match(workspaceSource, /:items="sectionItems"/)
  assert.match(workspaceSource, /:describe-item="describeItem"/)
  assert.match(workspaceSource, /:resolve-card-icon="resolveCardIcon"/)
  assert.match(workspaceSource, /:project-menu-options="projectMenuOptions"/)
  assert.doesNotMatch(workspaceSource, /<WorkspaceCardsGrid[\s\S]*@create-project="createBlankProject"[\s\S]*\/>/)
  assert.match(workspaceSource, /@primary-click="handlePrimaryClick"/)
  assert.match(workspaceSource, /@project-menu-select="handleProjectMenuSelect"/)
  assert.doesNotMatch(workspaceSource, /<WorkspaceCardsGrid[\s\S]*@preview-template="openTemplatePreview"[\s\S]*\/>/)
  assert.doesNotMatch(workspaceSource, /<WorkspaceCardsGrid[\s\S]*@use-template="useTemplate"[\s\S]*\/>/)
  assert.doesNotMatch(workspaceSource, /<section class="cards-grid"/)
  assert.doesNotMatch(workspaceSource, /\.cards-grid\s*\{/)
  assert.doesNotMatch(workspaceSource, /\.project-card\s*\{/)
  assert.doesNotMatch(workspaceSource, /\.project-meta-row\s*\{/)

  assert.match(cardsGridSource, /import \{ BaseDropdown \} from '@\/components\/ui'/)
  assert.match(cardsGridSource, /import WorkspaceTemplateCanvasPreview from '\.\/WorkspaceTemplateCanvasPreview\.vue'/)
  assert.match(cardsGridSource, /<section class="cards-grid"/)
  assert.match(cardsGridSource, /:class="`cards-grid--\$\{activeSection\}`"/)
  assert.doesNotMatch(cardsGridSource, /class="project-card create-card"/)
  assert.doesNotMatch(cardsGridSource, /Blank Project/)
  assert.doesNotMatch(cardsGridSource, /Create a new blank project/)
  assert.doesNotMatch(cardsGridSource, /\$emit\('createProject'\)/)
  assert.match(cardsGridSource, /v-for="item in items"/)
  assert.match(cardsGridSource, /@click="\$emit\('primaryClick', item\)"/)
  assert.match(cardsGridSource, /:options="projectMenuOptions\(item\)"/)
  assert.match(cardsGridSource, /@select="\(key\) => \$emit\('projectMenuSelect', key, item\)"/)
  assert.doesNotMatch(cardsGridSource, /class="card-actions"/)
  assert.match(cardsGridSource, /activeSection === 'featured' && item\.canvasData/)
  assert.match(cardsGridSource, /<WorkspaceTemplateCanvasPreview[\s\S]*:canvas-data="item\.canvasData"/)
  assert.match(cardsGridSource, /class="card-canvas-preview"/)
  assert.match(cardsGridSource, /\.cards-grid--featured\s*\{[^}]*minmax\(420px,\s*1fr\)/s)
  assert.doesNotMatch(cardsGridSource, /\$emit\('previewTemplate'/)
  assert.doesNotMatch(cardsGridSource, /\$emit\('useTemplate'/)
  assert.match(cardsGridSource, /defineEmits\(\[\s*'primaryClick'/s)
  assert.match(cardsGridSource, /\.cards-grid\s*\{/)
  assert.match(cardsGridSource, /\.project-meta-row\s*\{/)
})

test('workspace switcher falls back to the user-derived workspace brand', () => {
  const switcherSource = readWorkspaceComponentSource('WorkspaceSwitcher')

  assert.match(switcherSource, /fallbackName/)
  assert.match(switcherSource, /currentWorkspace\?\.name \|\| fallbackName/)
  assert.doesNotMatch(switcherSource, /currentWorkspace\?\.name \|\| 'Personal Workspace'/)
})

test('workspace cards show owner avatars only on shared and template surfaces', () => {
  const cardsGridSource = readWorkspaceComponentSource('WorkspaceCardsGrid')

  assert.match(cardsGridSource, /showOwnerAvatar\(item,\s*activeSection\)/)
  assert.match(cardsGridSource, /if \(activeSection === 'projects'\) return false/)
  assert.match(cardsGridSource, /if \(activeSection === 'shared'\) return true/)
  assert.match(cardsGridSource, /if \(activeSection === 'featured'\)/)
})

test('workspace shared templates render an empty state instead of a blank panel', () => {
  const cardsGridSource = readWorkspaceComponentSource('WorkspaceCardsGrid')

  assert.match(cardsGridSource, /v-if="!items\.length"/)
  assert.match(cardsGridSource, /class="cards-empty-state"/)
  assert.match(cardsGridSource, /No shared templates yet/)
  assert.match(cardsGridSource, /\.cards-empty-state\s*\{/)
})

test('workspace project card hover outline stays inside the cover media', () => {
  const cardsGridSource = readWorkspaceComponentSource('WorkspaceCardsGrid')

  assert.doesNotMatch(cardsGridSource, /\.project-card\s*\{[^}]*box-shadow:\s*0 0 0 1px transparent/s)
  assert.doesNotMatch(cardsGridSource, /\.project-card:hover,\s*\.project-card:focus-within\s*\{[^}]*box-shadow/s)
  assert.match(cardsGridSource, /\.card-media\s*\{[^}]*position:\s*relative/s)
  assert.match(cardsGridSource, /\.card-media\s*\{[^}]*overflow:\s*hidden/s)
  assert.match(cardsGridSource, /\.card-media::after\s*\{[^}]*inset:\s*0/s)
  assert.match(cardsGridSource, /\.card-media::after\s*\{[^}]*opacity:\s*0/s)
  assert.match(cardsGridSource, /\.project-card:hover \.card-media::after,\s*\.project-card:focus-within \.card-media::after\s*\{[^}]*opacity:\s*1/s)
  assert.match(cardsGridSource, /@media\s*\(prefers-reduced-motion:\s*reduce\)/)
})

test('workspace view delegates project and template modals to a focused component', () => {
  const modalsSource = readWorkspaceComponentSource('WorkspaceModals')

  assert.match(workspaceSource, /import WorkspaceModals from '@\/components\/workspace\/WorkspaceModals\.vue'/)
  assert.equal([...workspaceSource.matchAll(/<WorkspaceModals\b/g)].length, 1)
  assert.match(workspaceSource, /v-model:show-rename="showRenameModal"/)
  assert.match(workspaceSource, /v-model:show-delete="showDeleteModal"/)
  assert.match(workspaceSource, /v-model:show-template-preview="showTemplatePreviewModal"/)
  assert.match(workspaceSource, /v-model:rename-value="renameValue"/)
  assert.match(workspaceSource, /:delete-target-name="deleteTargetName"/)
  assert.match(workspaceSource, /:preview-template="previewTemplate"/)
  assert.match(workspaceSource, /@confirm-rename="confirmRename"/)
  assert.match(workspaceSource, /@confirm-delete="confirmDelete"/)
  assert.match(workspaceSource, /@close-template-preview="closeTemplatePreview"/)
  assert.match(workspaceSource, /@use-template-from-preview="useTemplateFromPreview"/)
  assert.doesNotMatch(workspaceSource, /<BaseModal/)
  assert.doesNotMatch(workspaceSource, /import \{ BaseButton, BaseInput, BaseModal, BaseModalActions, BaseModalCopy \}/)
  assert.doesNotMatch(workspaceSource, /\.template-preview\s*\{/)
  assert.doesNotMatch(workspaceSource, /\.template-preview-media\s*\{/)

  assert.match(modalsSource, /import \{ computed \} from 'vue'/)
  assert.match(modalsSource, /import \{ BaseButton, BaseInput, BaseModal, BaseModalActions, BaseModalCopy \} from '@\/components\/ui'/)
  assert.match(modalsSource, /import WorkspaceTemplateCanvasPreview from '\.\/WorkspaceTemplateCanvasPreview\.vue'/)
  assert.match(modalsSource, /import \{ getWorkspaceTemplateNodeCount \} from '@\/utils\/workspaceTemplatePreview'/)
  assert.match(modalsSource, /title="Rename project"/)
  assert.match(modalsSource, /title="Delete project"/)
  assert.match(modalsSource, /title="Template Preview"/)
  assert.match(modalsSource, /<WorkspaceTemplateCanvasPreview[\s\S]*:canvas-data="previewTemplate\.canvasData"/)
  assert.match(modalsSource, /templateNodeCount/)
  assert.match(modalsSource, /template-preview-stat/)
  assert.match(modalsSource, /\.template-preview-stat\s*\{[^}]*border:\s*none/s)
  assert.match(modalsSource, /\.template-preview-stat\s*\{[^}]*padding:\s*0/s)
  assert.match(modalsSource, /\.template-preview-stat\s*\{[^}]*background:\s*transparent/s)
  assert.match(modalsSource, /\.template-preview-stat\s*\{[^}]*border-radius:\s*0/s)
  assert.doesNotMatch(modalsSource, /No cover/)
  assert.match(modalsSource, /v-model="renameValueModel"/)
  assert.match(modalsSource, /BaseModalCopy>Delete "\{\{ deleteTargetName \}\}"/)
  assert.match(modalsSource, /@click="\$emit\('confirmRename'\)"/)
  assert.match(modalsSource, /@click="\$emit\('confirmDelete'\)"/)
  assert.match(modalsSource, /@click="\$emit\('closeTemplatePreview'\)"/)
  assert.match(modalsSource, /@click="\$emit\('useTemplateFromPreview'\)"/)
  assert.match(modalsSource, /emit\('update:renameValue', value\)/)
  assert.match(modalsSource, /\.template-preview\s*\{/)
  assert.match(modalsSource, /\.template-preview-description\s*\{/)
  assert.match(modalsSource, /\.template-preview-content\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\) auto/s)
})

test('workspace profile modal exposes avatar, display name, email, and user id surfaces', () => {
  const profileModalSource = readWorkspaceComponentSource('WorkspaceProfileModal')

  assert.match(profileModalSource, /title="Profile settings"/)
  assert.match(profileModalSource, /@click="\$emit\('uploadAvatar'\)"/)
  assert.match(profileModalSource, /v-model="displayNameModel"/)
  assert.match(profileModalSource, /label="Display Name"/)
  assert.match(profileModalSource, /label="Email"/)
  assert.match(profileModalSource, /label="User ID"/)
  assert.match(profileModalSource, /readonly/)
  assert.match(profileModalSource, /@click="\$emit\('saveProfile'\)"/)
})

test('workspace team modals expose create workspace slug, avatar, and invite surfaces', () => {
  const teamModalsSource = readWorkspaceComponentSource('WorkspaceTeamModals')

  assert.match(workspaceSource, /import WorkspaceTeamModals from '@\/components\/workspace\/WorkspaceTeamModals\.vue'/)
  assert.match(workspaceSource, /v-model:create-name="createWorkspaceName"/)
  assert.match(workspaceSource, /v-model:create-avatar-url="createWorkspaceAvatarUrl"/)
  assert.match(workspaceSource, /:created-invite-url="createdWorkspaceInviteUrl"/)
  assert.match(workspaceSource, /@confirm-create="confirmCreateWorkspace"/)
  assert.match(teamModalsSource, /title="Create Workspace"/)
  assert.match(teamModalsSource, /<template #header>/)
  assert.match(teamModalsSource, /class="create-modal-heading"/)
  assert.match(teamModalsSource, /\.create-modal-heading\s*\{[^}]*gap:\s*0/s)
  assert.match(teamModalsSource, /class="create-workspace-layout"/)
  assert.match(teamModalsSource, /class="avatar-panel"/)
  assert.match(teamModalsSource, /class="create-form-stack"/)
  assert.match(teamModalsSource, /aria-label="Choose team avatar"/)
  assert.match(teamModalsSource, /\.create-form-stack\s+:deep\(input\.ui-body\)\s*\{[^}]*padding-left:\s*10px/s)
  assert.match(teamModalsSource, /\.create-form-stack\s+:deep\(input\.ui-body\)\s*\{[^}]*padding-right:\s*10px/s)
  assert.match(teamModalsSource, /\.create-form-stack\s+:deep\(input\.ui-body\)\s*\{[^}]*font-size:\s*14px/s)
  assert.doesNotMatch(teamModalsSource, /avatar-upload-label/)
  assert.doesNotMatch(teamModalsSource, />\s*Upload team avatar\s*</)
  assert.match(teamModalsSource, /\.create-workspace-layout\s*\{[^}]*align-items:\s*center/s)
  assert.match(teamModalsSource, /\.avatar-panel\s*\{[^}]*align-items:\s*center/s)
  assert.match(teamModalsSource, /\.avatar-panel\s*\{[^}]*justify-content:\s*center/s)
  assert.match(teamModalsSource, /\.avatar-upload\s*\{[^}]*width:\s*100px/s)
  assert.match(teamModalsSource, /\.avatar-upload\s*\{[^}]*height:\s*100px/s)
  assert.match(teamModalsSource, /\.avatar-upload\s*\{[^}]*border-radius:\s*60px/s)
  assert.match(teamModalsSource, /\.avatar-upload\s*\{[^}]*font-size:\s*25px/s)
  assert.match(teamModalsSource, /label="Workspace Name"/)
  assert.doesNotMatch(teamModalsSource, /@keyup\.enter="\$emit\('confirmCreate'\)"/)
  assert.match(teamModalsSource, /URL Slug/)
  assert.match(teamModalsSource, /const generatedSlug = computed/)
  assert.match(teamModalsSource, /Invite link · 7 days/)
  assert.match(teamModalsSource, /Username or email/)
  assert.match(teamModalsSource, /Transfer to/)
})

test('workspace team modals expose edit and delete workspace flows', () => {
  const teamModalsSource = readWorkspaceComponentSource('WorkspaceTeamModals')

  assert.match(workspaceSource, /v-model:show-edit="showEditWorkspaceModal"/)
  assert.match(workspaceSource, /v-model:show-delete="showDeleteWorkspaceModal"/)
  assert.match(workspaceSource, /v-model:edit-name="editWorkspaceName"/)
  assert.match(workspaceSource, /v-model:edit-avatar-url="editWorkspaceAvatarUrl"/)
  assert.match(workspaceSource, /:delete-workspace-name="deleteWorkspaceName"/)
  assert.match(workspaceSource, /@confirm-edit="confirmEditWorkspace"/)
  assert.match(workspaceSource, /@confirm-delete-workspace="confirmDeleteWorkspace"/)
  assert.match(teamModalsSource, /title="Edit Workspace"/)
  assert.match(teamModalsSource, /aria-label="Choose updated team avatar"/)
  assert.match(teamModalsSource, /label="Workspace Name"/)
  assert.match(teamModalsSource, /title="Delete Workspace"/)
  assert.match(teamModalsSource, /Delete workspace "\{\{ deleteWorkspaceName \}\}"/)
})

test('workspace creation regenerates the created invite link without creating a duplicate team', () => {
  const start = workspaceSource.indexOf('const confirmCreateWorkspace = async () => {')
  const end = workspaceSource.indexOf('const openInviteWorkspaceModal = () => {')
  const branch = workspaceSource.slice(start, end)

  assert.match(branch, /if \(createdWorkspaceInviteUrl\.value\) \{/)
  assert.match(branch, /const invite = await createWorkspaceInviteLink\(currentWorkspace\.value\?\.id\)/)
  assert.match(branch, /notifier\.success\('Invite link regenerated'\)/)
  assert.match(branch, /return\s*\}/)
})

test('workspace template canvas preview renders capped image assets instead of a node graph', () => {
  const previewSource = readWorkspaceComponentSource('WorkspaceTemplateCanvasPreview')

  assert.match(previewSource, /getWorkspaceTemplatePreviewAssets/)
  assert.match(previewSource, /getWorkspaceTemplatePreviewGridSize/)
  assert.match(previewSource, /template-asset-wall/)
  assert.match(previewSource, /previewAssetsWithLayout/)
  assert.match(previewSource, /--template-preview-wall-columns/)
  assert.match(previewSource, /--template-preview-wall-rows/)
  assert.match(previewSource, /template-asset-tile--layout-/)
  assert.match(previewSource, /grid-template-rows:\s*repeat\(var\(--template-preview-wall-rows\)/)
  assert.match(previewSource, /v-for="asset in previewAssetsWithLayout"/)
  assert.match(previewSource, /:src="asset\.url"/)
  assert.match(previewSource, /loading="lazy"/)
  assert.match(previewSource, /decoding="async"/)
  assert.match(previewSource, /object-fit:\s*cover/)
  assert.match(previewSource, /width:\s*100%/)
  assert.match(previewSource, /height:\s*100%/)
  assert.match(previewSource, /template-asset-tile--layout-9-9/)
  assert.match(previewSource, /No image assets/)
  assert.doesNotMatch(previewSource, /template-asset-grid/)
  assert.doesNotMatch(previewSource, /object-fit:\s*contain/)
  assert.doesNotMatch(previewSource, /grid-auto-flow:\s*dense/)
  assert.doesNotMatch(previewSource, /getWorkspaceTemplatePreviewEdges/)
  assert.doesNotMatch(previewSource, /getWorkspaceTemplatePreviewNodes/)
  assert.doesNotMatch(previewSource, /<svg[\s\S]*class="template-canvas-edges"/)
  assert.doesNotMatch(previewSource, /class="template-canvas-edge"/)
  assert.doesNotMatch(previewSource, /class="template-canvas-node"/)
  assert.match(previewSource, /\.template-canvas-preview\s*\{[^}]*linear-gradient\(180deg,\s*#101010 0%,\s*#050505 100%\)/s)
  assert.doesNotMatch(previewSource, /\.template-canvas-preview\s*\{[^}]*rgba\(255,\s*255,\s*255,\s*0\.06\)/s)
  assert.doesNotMatch(previewSource, /\.template-canvas-preview\s*\{[^}]*#17181c/s)
  assert.doesNotMatch(previewSource, /min-width:\s*70px/)
  assert.doesNotMatch(previewSource, /min-height:\s*42px/)
})

test('workspace view delegates display copy and card derivation to workspace display helpers', () => {
  const displaySource = readWorkspaceUtilsSource('workspaceDisplay')

  assert.match(workspaceSource, /import \{[\s\S]*getWorkspaceBrand[\s\S]*getWorkspaceSectionTitle[\s\S]*getWorkspaceProjectMenuOptions[\s\S]*\} from '@\/utils\/workspaceDisplay'/)
  assert.match(workspaceSource, /getWorkspaceBrand\(\{[\s\S]*user: user\.value[\s\S]*currentWorkspace: currentWorkspace\.value[\s\S]*\}\)/)
  assert.match(workspaceSource, /getWorkspaceSectionTitle\(activeSection\.value\)/)
  assert.match(workspaceSource, /getWorkspaceSectionDescription\(activeSection\.value\)/)
  assert.match(workspaceSource, /describeWorkspaceItem\(\{[\s\S]*activeSection: activeSection\.value[\s\S]*item[\s\S]*\}\)/)
  assert.match(workspaceSource, /getWorkspaceCardIconKey\(\{[\s\S]*activeSection: activeSection\.value[\s\S]*item[\s\S]*\}\)/)
  assert.match(workspaceSource, /ImageOutline/)
  assert.match(workspaceSource, /image:\s*ImageOutline/)
  assert.match(workspaceSource, /const projectMenuOptions = getWorkspaceProjectMenuOptions/)
  assert.doesNotMatch(workspaceSource, /const formatDate =/)
  assert.doesNotMatch(workspaceSource, /const projectMenuOptions = \(\) => \[/)
  assert.doesNotMatch(workspaceSource, /Templates published by workspace members/)

  assert.match(displaySource, /export const getWorkspaceBrand/)
  assert.match(displaySource, /export const getWorkspaceSectionTitle/)
  assert.match(displaySource, /export const getWorkspaceSectionDescription/)
  assert.match(displaySource, /export const describeWorkspaceItem/)
  assert.match(displaySource, /export const getWorkspaceCardIconKey/)
  assert.match(displaySource, /export const getWorkspaceProjectMenuOptions/)
})


test('workspace project card navigation does not block on a cloud detail refresh', () => {
  const start = workspaceSource.indexOf('const handlePrimaryClick = async (item) => {')
  const end = workspaceSource.indexOf('const refreshProjectFromCloud = async')
  const branch = workspaceSource.slice(start, end)

  assert.match(branch, /await router\.push\(`\/canvas\/\$\{item\.id\}`\)/)
  assert.doesNotMatch(branch, /await refreshProjectById\(item\.id\)/)
  assert.doesNotMatch(branch, /Keep the local draft path available/)
})

test('workspace cloud surfaces fail softly while project list stays cloud authoritative', () => {
  assert.match(workspaceSource, /const loadWorkspaceSurfaces = async \(\) => \{/)
  assert.match(workspaceSource, /try\s*\{\s*await loadCurrentWorkspace\(\)\s*await loadWorkspaces\(\)\s*\}\s*catch/s)
  assert.match(workspaceSource, /try\s*\{\s*await loadPendingWorkspaceInvites\(\)\s*\}\s*catch/s)
  assert.match(workspaceSource, /try\s*\{\s*await loadFeaturedTemplates\(activeTemplateScope\.value\)\s*\}\s*catch/s)
  assert.match(workspaceSource, /await loadWorkspaceProjects\(\)[\s\S]*await loadWorkspaceSurfaces\(\)/)
})

test('workspace project list does not render browser local cache as authoritative data', () => {
  assert.match(projectsStoreSource, /export const loadProjects = async \(\{ allowLocalFallback = true \} = \{\}\) => \{/)
  assert.match(projectsStoreSource, /if \(!allowLocalFallback\)\s*\{[\s\S]*projects\.value = \[\][\s\S]*source:\s*'remote-error'/)
  assert.match(projectsStoreSource, /export const initProjectsStore = async \(options = \{\}\) => \{\s*await loadProjects\(options\)\s*\}/)
  assert.match(workspaceSource, /const loadWorkspaceProjects = async \(\) => \{\s*await initProjectsStore\(\{ allowLocalFallback: false \}\)\s*\}/)
  assert.match(workspaceSource, /:empty-state-title="cardsEmptyStateTitle"/)
  assert.match(workspaceSource, /Project list unavailable/)
})

test('workspace template scope follows the effective backend scope after loading', () => {
  const storeSource = readFileSync(new URL('../stores/workspace.js', import.meta.url), 'utf8')

  assert.match(workspaceSource, /const activeTemplateScope = ref\('community'\)/)
  assert.match(workspaceSource, /syncActiveTemplateScopeFromStore\(\)/)
  assert.match(storeSource, /templatesScope\.value = response\?\.data\?\.scope \|\| templatesScope\.value/)
})
