import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { test } from 'node:test'

const workspaceSource = readFileSync(new URL('./Workspace.vue', import.meta.url), 'utf8')
const styleSource = readFileSync(new URL('../style.css', import.meta.url), 'utf8')
const iconsSource = readFileSync(new URL('../icons/coolicons.js', import.meta.url), 'utf8')

function readWorkspaceComponentSource(name) {
  const path = fileURLToPath(new URL(`../components/workspace/${name}.vue`, import.meta.url))
  return existsSync(path) ? readFileSync(path, 'utf8') : ''
}

function readWorkspaceUtilsSource(name) {
  const path = fileURLToPath(new URL(`../utils/${name}.js`, import.meta.url))
  return existsSync(path) ? readFileSync(path, 'utf8') : ''
}

test('workspace view delegates the main header to a focused component', () => {
  const headerSource = readWorkspaceComponentSource('WorkspaceHeader')
  const actionPillSource = readWorkspaceComponentSource('WorkspaceActionPill')

  assert.match(workspaceSource, /import WorkspaceHeader from '@\/components\/workspace\/WorkspaceHeader\.vue'/)
  assert.equal([...workspaceSource.matchAll(/<WorkspaceHeader\b/g)].length, 1)
  assert.match(workspaceSource, /:title="sectionTitle"/)
  assert.match(workspaceSource, /:description="sectionDescription"/)
  assert.match(workspaceSource, /@back-home="router\.push\('\/'\)"/)
  assert.match(workspaceSource, /@create-project="createBlankProject"/)
  assert.doesNotMatch(workspaceSource, /import WorkspaceActionPill/)
  assert.doesNotMatch(workspaceSource, /<WorkspaceActionPill[\s>]/)
  assert.doesNotMatch(workspaceSource, /<header class="main-header"/)
  assert.doesNotMatch(workspaceSource, /\.main-header\s*\{/)
  assert.doesNotMatch(workspaceSource, /\.header-actions\s*\{/)
  assert.doesNotMatch(workspaceSource, /ui-action-pill/)
  assert.doesNotMatch(styleSource, /\.ui-action-pill(?:\s|\.|:|\{)/)

  assert.match(headerSource, /import WorkspaceActionPill from '\.\/WorkspaceActionPill\.vue'/)
  assert.match(headerSource, /<header class="main-header">/)
  assert.match(headerSource, /\{\{ title \}\}/)
  assert.match(headerSource, /\{\{ description \}\}/)
  assert.match(headerSource, /@click="\$emit\('backHome'\)"/)
  assert.match(headerSource, /@click="\$emit\('createProject'\)"/)
  assert.match(headerSource, /<WorkspaceActionPill\s+variant="primary"\s+@click="\$emit\('createProject'\)"/)
  assert.match(headerSource, /defineEmits\(\['backHome', 'createProject'\]\)/)
  assert.match(headerSource, /\.main-header\s*\{/)
  assert.match(headerSource, /\.header-actions\s*\{/)
  assert.match(actionPillSource, /'workspace-action-pill'/)
  assert.match(actionPillSource, /class="workspace-action-pill-label"/)
  assert.match(actionPillSource, /variant:\s*\{[\s\S]*default:\s*'default'/)
  assert.match(actionPillSource, /`workspace-action-pill--\$\{props\.variant\}`/)
  assert.match(actionPillSource, /\.workspace-action-pill--primary\s*\{[^}]*background:\s*#fff/s)
  assert.match(actionPillSource, /\.workspace-action-pill--primary\s*\{[^}]*color:\s*#0d0e10/s)
  assert.match(actionPillSource, /defineEmits\(\['click'\]\)/)
  assert.match(actionPillSource, /\.workspace-action-pill\s*\{[^}]*display:\s*inline-flex/s)
  assert.match(actionPillSource, /\.workspace-action-pill-label\s*\{[^}]*font-size:\s*15px/s)
})

test('workspace view delegates sidebar navigation and account chrome to a focused component', () => {
  const sidebarSource = readWorkspaceComponentSource('WorkspaceSidebar')

  assert.match(workspaceSource, /import WorkspaceSidebar from '@\/components\/workspace\/WorkspaceSidebar\.vue'/)
  assert.equal([...workspaceSource.matchAll(/<WorkspaceSidebar\b/g)].length, 1)
  assert.match(workspaceSource, /v-model:active-section="activeSection"/)
  assert.match(workspaceSource, /:workspace-brand="workspaceBrand"/)
  assert.match(workspaceSource, /:nav-items="navItems"/)
  assert.match(workspaceSource, /:is-authenticated="isAuthenticated"/)
  assert.match(workspaceSource, /:user="user"/)
  assert.match(workspaceSource, /:avatar-initial="avatarInitial"/)
  assert.match(workspaceSource, /@upload-avatar="triggerAvatarUpload"/)
  assert.match(workspaceSource, /@logout="handleLogout"/)
  assert.doesNotMatch(workspaceSource, /<aside class="workspace-sidebar"/)
  assert.doesNotMatch(workspaceSource, /\.workspace-sidebar\s*\{/)
  assert.doesNotMatch(workspaceSource, /\.sidebar-account\s*\{/)
  assert.doesNotMatch(workspaceSource, /\.account-action-btn\s*\{/)

  assert.match(sidebarSource, /<aside class="workspace-sidebar">/)
  assert.match(sidebarSource, /import aioncraftWordmark from '@\/assets\/home-figma\/aioncraft-wordmark\.svg'/)
  assert.match(sidebarSource, /<img\s+:src="aioncraftWordmark"\s+alt="AionCraft"\s+class="brand-logo"/)
  assert.match(sidebarSource, /<span class="brand-divider" aria-hidden="true"><\/span>/)
  assert.match(sidebarSource, /\.brand\s*\{[^}]*gap:\s*16px/s)
  assert.match(sidebarSource, /\.brand-divider\s*\{[^}]*width:\s*1px/s)
  assert.match(sidebarSource, /\.brand-divider\s*\{[^}]*height:\s*28px/s)
  assert.doesNotMatch(sidebarSource, /src="\/project-logo\.svg"/)
  assert.match(sidebarSource, /v-for="item in navItems"/)
  assert.match(sidebarSource, /:class="\{ active: activeSection === item\.key \}"/)
  assert.match(sidebarSource, /@click="\$emit\('update:activeSection', item\.key\)"/)
  assert.match(sidebarSource, /@click="\$emit\('uploadAvatar'\)"/)
  assert.match(sidebarSource, /@click="\$emit\('usage'\)"/)
  assert.match(sidebarSource, /@click="\$emit\('logout'\)"/)
  assert.match(sidebarSource, /@click="\$emit\('login'\)"/)
  assert.match(sidebarSource, /@click="\$emit\('register'\)"/)
  assert.match(sidebarSource, /defineEmits\(\[\s*'update:activeSection'/s)
  assert.match(sidebarSource, /\.workspace-sidebar\s*\{/)
  assert.match(sidebarSource, /\.account-action-btn-primary:hover\s*\{/)
  assert.match(workspaceSource, /GlobeOutline/)
  assert.match(workspaceSource, /\{ key: 'featured', label: 'Share Templates', icon: GlobeOutline \}/)
  assert.match(iconsSource, /import globe from '@iconify-icons\/ci\/globe'/)
  assert.match(iconsSource, /export const GlobeOutline = wrap\(globe\)/)
})

test('workspace view delegates project and template cards to a focused component', () => {
  const cardsGridSource = readWorkspaceComponentSource('WorkspaceCardsGrid')

  assert.match(workspaceSource, /import WorkspaceCardsGrid from '@\/components\/workspace\/WorkspaceCardsGrid\.vue'/)
  assert.equal([...workspaceSource.matchAll(/<WorkspaceCardsGrid\b/g)].length, 1)
  assert.match(workspaceSource, /:active-section="activeSection"/)
  assert.match(workspaceSource, /:items="sectionItems"/)
  assert.match(workspaceSource, /:describe-item="describeItem"/)
  assert.match(workspaceSource, /:resolve-card-icon="resolveCardIcon"/)
  assert.match(workspaceSource, /:project-menu-options="projectMenuOptions"/)
  assert.doesNotMatch(workspaceSource, /<WorkspaceCardsGrid[\s\S]*@create-project="createBlankProject"[\s\S]*\/>/)
  assert.match(workspaceSource, /@primary-click="handlePrimaryClick"/)
  assert.match(workspaceSource, /@project-menu-select="handleProjectMenuSelect"/)
  assert.doesNotMatch(workspaceSource, /<WorkspaceCardsGrid[\s\S]*@preview-template="openTemplatePreview"[\s\S]*\/>/)
  assert.doesNotMatch(workspaceSource, /<WorkspaceCardsGrid[\s\S]*@use-template="useTemplate"[\s\S]*\/>/)
  assert.doesNotMatch(workspaceSource, /<section class="cards-grid"/)
  assert.doesNotMatch(workspaceSource, /\.cards-grid\s*\{/)
  assert.doesNotMatch(workspaceSource, /\.project-card\s*\{/)
  assert.doesNotMatch(workspaceSource, /\.project-meta-row\s*\{/)

  assert.match(cardsGridSource, /import \{ BaseDropdown \} from '@\/components\/ui'/)
  assert.match(cardsGridSource, /import WorkspaceTemplateCanvasPreview from '\.\/WorkspaceTemplateCanvasPreview\.vue'/)
  assert.match(cardsGridSource, /<section class="cards-grid"/)
  assert.match(cardsGridSource, /:class="`cards-grid--\$\{activeSection\}`"/)
  assert.doesNotMatch(cardsGridSource, /class="project-card create-card"/)
  assert.doesNotMatch(cardsGridSource, /Blank Project/)
  assert.doesNotMatch(cardsGridSource, /Create a new blank project/)
  assert.doesNotMatch(cardsGridSource, /\$emit\('createProject'\)/)
  assert.match(cardsGridSource, /v-for="item in items"/)
  assert.match(cardsGridSource, /@click="\$emit\('primaryClick', item\)"/)
  assert.match(cardsGridSource, /:options="projectMenuOptions\(item\)"/)
  assert.match(cardsGridSource, /@select="\(key\) => \$emit\('projectMenuSelect', key, item\)"/)
  assert.doesNotMatch(cardsGridSource, /class="card-actions"/)
  assert.match(cardsGridSource, /activeSection === 'featured' && item\.canvasData/)
  assert.match(cardsGridSource, /<WorkspaceTemplateCanvasPreview[\s\S]*:canvas-data="item\.canvasData"/)
  assert.match(cardsGridSource, /class="card-canvas-preview"/)
  assert.match(cardsGridSource, /\.cards-grid--featured\s*\{[^}]*minmax\(420px,\s*1fr\)/s)
  assert.doesNotMatch(cardsGridSource, /\$emit\('previewTemplate'/)
  assert.doesNotMatch(cardsGridSource, /\$emit\('useTemplate'/)
  assert.match(cardsGridSource, /defineEmits\(\[\s*'primaryClick'/s)
  assert.match(cardsGridSource, /\.cards-grid\s*\{/)
  assert.match(cardsGridSource, /\.project-meta-row\s*\{/)
})

test('workspace project card hover outline stays inside the cover media', () => {
  const cardsGridSource = readWorkspaceComponentSource('WorkspaceCardsGrid')

  assert.doesNotMatch(cardsGridSource, /\.project-card\s*\{[^}]*box-shadow:\s*0 0 0 1px transparent/s)
  assert.doesNotMatch(cardsGridSource, /\.project-card:hover,\s*\.project-card:focus-within\s*\{[^}]*box-shadow/s)
  assert.match(cardsGridSource, /\.card-media\s*\{[^}]*position:\s*relative/s)
  assert.match(cardsGridSource, /\.card-media\s*\{[^}]*overflow:\s*hidden/s)
  assert.match(cardsGridSource, /\.card-media::after\s*\{[^}]*inset:\s*0/s)
  assert.match(cardsGridSource, /\.card-media::after\s*\{[^}]*opacity:\s*0/s)
  assert.match(cardsGridSource, /\.project-card:hover \.card-media::after,\s*\.project-card:focus-within \.card-media::after\s*\{[^}]*opacity:\s*1/s)
  assert.match(cardsGridSource, /@media\s*\(prefers-reduced-motion:\s*reduce\)/)
})

test('workspace view delegates project and template modals to a focused component', () => {
  const modalsSource = readWorkspaceComponentSource('WorkspaceModals')

  assert.match(workspaceSource, /import WorkspaceModals from '@\/components\/workspace\/WorkspaceModals\.vue'/)
  assert.equal([...workspaceSource.matchAll(/<WorkspaceModals\b/g)].length, 1)
  assert.match(workspaceSource, /v-model:show-rename="showRenameModal"/)
  assert.match(workspaceSource, /v-model:show-delete="showDeleteModal"/)
  assert.match(workspaceSource, /v-model:show-template-preview="showTemplatePreviewModal"/)
  assert.match(workspaceSource, /v-model:rename-value="renameValue"/)
  assert.match(workspaceSource, /:delete-target-name="deleteTargetName"/)
  assert.match(workspaceSource, /:preview-template="previewTemplate"/)
  assert.match(workspaceSource, /@confirm-rename="confirmRename"/)
  assert.match(workspaceSource, /@confirm-delete="confirmDelete"/)
  assert.match(workspaceSource, /@close-template-preview="closeTemplatePreview"/)
  assert.match(workspaceSource, /@use-template-from-preview="useTemplateFromPreview"/)
  assert.doesNotMatch(workspaceSource, /<BaseModal/)
  assert.doesNotMatch(workspaceSource, /import \{ BaseButton, BaseInput, BaseModal, BaseModalActions, BaseModalCopy \}/)
  assert.doesNotMatch(workspaceSource, /\.template-preview\s*\{/)
  assert.doesNotMatch(workspaceSource, /\.template-preview-media\s*\{/)

  assert.match(modalsSource, /import \{ computed \} from 'vue'/)
  assert.match(modalsSource, /import \{ BaseButton, BaseInput, BaseModal, BaseModalActions, BaseModalCopy \} from '@\/components\/ui'/)
  assert.match(modalsSource, /import WorkspaceTemplateCanvasPreview from '\.\/WorkspaceTemplateCanvasPreview\.vue'/)
  assert.match(modalsSource, /import \{ getWorkspaceTemplateNodeCount \} from '@\/utils\/workspaceTemplatePreview'/)
  assert.match(modalsSource, /title="Rename project"/)
  assert.match(modalsSource, /title="Delete project"/)
  assert.match(modalsSource, /title="Template Preview"/)
  assert.match(modalsSource, /<WorkspaceTemplateCanvasPreview[\s\S]*:canvas-data="previewTemplate\.canvasData"/)
  assert.match(modalsSource, /templateNodeCount/)
  assert.match(modalsSource, /template-preview-stat/)
  assert.match(modalsSource, /\.template-preview-stat\s*\{[^}]*border:\s*none/s)
  assert.match(modalsSource, /\.template-preview-stat\s*\{[^}]*padding:\s*0/s)
  assert.match(modalsSource, /\.template-preview-stat\s*\{[^}]*background:\s*transparent/s)
  assert.match(modalsSource, /\.template-preview-stat\s*\{[^}]*border-radius:\s*0/s)
  assert.doesNotMatch(modalsSource, /No cover/)
  assert.match(modalsSource, /v-model="renameValueModel"/)
  assert.match(modalsSource, /BaseModalCopy>Delete "\{\{ deleteTargetName \}\}"/)
  assert.match(modalsSource, /@click="\$emit\('confirmRename'\)"/)
  assert.match(modalsSource, /@click="\$emit\('confirmDelete'\)"/)
  assert.match(modalsSource, /@click="\$emit\('closeTemplatePreview'\)"/)
  assert.match(modalsSource, /@click="\$emit\('useTemplateFromPreview'\)"/)
  assert.match(modalsSource, /emit\('update:renameValue', value\)/)
  assert.match(modalsSource, /\.template-preview\s*\{/)
  assert.match(modalsSource, /\.template-preview-description\s*\{/)
  assert.match(modalsSource, /\.template-preview-content\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\) auto/s)
})

test('workspace template canvas preview renders capped image assets instead of a node graph', () => {
  const previewSource = readWorkspaceComponentSource('WorkspaceTemplateCanvasPreview')

  assert.match(previewSource, /getWorkspaceTemplatePreviewAssets/)
  assert.match(previewSource, /getWorkspaceTemplatePreviewGridSize/)
  assert.match(previewSource, /template-asset-grid/)
  assert.match(previewSource, /--template-preview-grid-size/)
  assert.match(previewSource, /v-for="asset in previewAssets"/)
  assert.match(previewSource, /:src="asset\.url"/)
  assert.match(previewSource, /loading="lazy"/)
  assert.match(previewSource, /decoding="async"/)
  assert.match(previewSource, /object-fit:\s*contain/)
  assert.match(previewSource, /No image assets/)
  assert.doesNotMatch(previewSource, /getWorkspaceTemplatePreviewEdges/)
  assert.doesNotMatch(previewSource, /getWorkspaceTemplatePreviewNodes/)
  assert.doesNotMatch(previewSource, /<svg[\s\S]*class="template-canvas-edges"/)
  assert.doesNotMatch(previewSource, /class="template-canvas-edge"/)
  assert.doesNotMatch(previewSource, /class="template-canvas-node"/)
  assert.match(previewSource, /\.template-canvas-preview\s*\{[^}]*linear-gradient\(180deg,\s*#101010 0%,\s*#050505 100%\)/s)
  assert.doesNotMatch(previewSource, /\.template-canvas-preview\s*\{[^}]*rgba\(255,\s*255,\s*255,\s*0\.06\)/s)
  assert.doesNotMatch(previewSource, /\.template-canvas-preview\s*\{[^}]*#17181c/s)
  assert.doesNotMatch(previewSource, /min-width:\s*70px/)
  assert.doesNotMatch(previewSource, /min-height:\s*42px/)
})

test('workspace view delegates display copy and card derivation to workspace display helpers', () => {
  const displaySource = readWorkspaceUtilsSource('workspaceDisplay')

  assert.match(workspaceSource, /import \{[\s\S]*getWorkspaceBrand[\s\S]*getWorkspaceSectionTitle[\s\S]*getWorkspaceProjectMenuOptions[\s\S]*\} from '@\/utils\/workspaceDisplay'/)
  assert.match(workspaceSource, /getWorkspaceBrand\(\{[\s\S]*user: user\.value[\s\S]*currentWorkspace: currentWorkspace\.value[\s\S]*\}\)/)
  assert.match(workspaceSource, /getWorkspaceSectionTitle\(activeSection\.value\)/)
  assert.match(workspaceSource, /getWorkspaceSectionDescription\(activeSection\.value\)/)
  assert.match(workspaceSource, /describeWorkspaceItem\(\{[\s\S]*activeSection: activeSection\.value[\s\S]*item[\s\S]*\}\)/)
  assert.match(workspaceSource, /getWorkspaceCardIconKey\(\{[\s\S]*activeSection: activeSection\.value[\s\S]*item[\s\S]*\}\)/)
  assert.match(workspaceSource, /ImageOutline/)
  assert.match(workspaceSource, /image:\s*ImageOutline/)
  assert.match(workspaceSource, /const projectMenuOptions = getWorkspaceProjectMenuOptions/)
  assert.doesNotMatch(workspaceSource, /const formatDate =/)
  assert.doesNotMatch(workspaceSource, /const projectMenuOptions = \(\) => \[/)
  assert.doesNotMatch(workspaceSource, /Templates published by workspace members/)

  assert.match(displaySource, /export const getWorkspaceBrand/)
  assert.match(displaySource, /export const getWorkspaceSectionTitle/)
  assert.match(displaySource, /export const getWorkspaceSectionDescription/)
  assert.match(displaySource, /export const describeWorkspaceItem/)
  assert.match(displaySource, /export const getWorkspaceCardIconKey/)
  assert.match(displaySource, /export const getWorkspaceProjectMenuOptions/)
})

test('workspace cloud surfaces fail softly so local projects remain accessible', () => {
  assert.match(workspaceSource, /const loadWorkspaceSurfaces = async \(\) => \{/)
  assert.match(workspaceSource, /try\s*\{\s*await loadCurrentWorkspace\(\)\s*\}\s*catch/s)
  assert.match(workspaceSource, /try\s*\{\s*await loadFeaturedTemplates\(\)\s*\}\s*catch/s)
  assert.match(workspaceSource, /await initProjectsStore\(\)[\s\S]*await loadWorkspaceSurfaces\(\)/)
})
