export const WORKFLOW_NAME_MAP = {
  '多角度分镜': 'Multi-Angle Storyboard',
  '通用产品全套电商图': 'E-commerce Product Set',
  '短剧角色设计': 'Character Design Pack',
  '多时段场景背景': 'Multi-Time Scene Pack',
  '绘本生成器': 'Storybook Generator'
}

export const LABEL_MAP = {
  '角色提示词': 'Character Prompt',
  '主角色图': 'Main Character',
  '角色图结果': 'Character Output',
  '产品信息': 'Product Info',
  '产品图片': 'Product Image',
  '模特图提示词': 'Model Shot Prompt',
  '侧面展示图提示词': 'Side Shot Prompt',
  '俯瞰展示图提示词': 'Top Shot Prompt',
  '拆解图提示词': 'Exploded View Prompt',
  '生成模特图': 'Generate Model Shot',
  '侧面展示图': 'Side Display',
  '俯瞰展示图': 'Top Display',
  '拆解图': 'Exploded View',
  '角色描述': 'Character Description',
  '风格参考图（可选）': 'Style Reference (Optional)',
  '正面全身提示词': 'Front Full-Body Prompt',
  '生成正面全身图': 'Generate Front Full-Body',
  '正面角色图（参考基准）': 'Front Reference Character',
  '侧面半身提示词': 'Side Half-Body Prompt',
  '表情特写提示词': 'Expression Close-Up Prompt',
  '背面全身提示词': 'Back Full-Body Prompt',
  '侧面半身图': 'Side Half-Body',
  '表情特写图': 'Expression Close-Up',
  '背面全身图': 'Back Full-Body',
  '场景描述': 'Scene Description',
  '基础场景提示词': 'Base Scene Prompt',
  '生成基础场景': 'Generate Base Scene',
  '基础场景图（参考基准）': 'Base Scene Reference',
  '傍晚场景提示词': 'Dusk Scene Prompt',
  '夜晚场景提示词': 'Night Scene Prompt',
  '雨天场景提示词': 'Rain Scene Prompt',
  '傍晚场景': 'Dusk Scene',
  '夜晚场景': 'Night Scene',
  '雨天场景': 'Rain Scene',
  '故事大纲': 'Story Outline',
  '角色设计提示词模板': 'Character Design Prompt Template',
  '角色设计生成': 'Generate Character Design',
  '主角色1设计图': 'Main Character 1 Design',
  '角色1:小白兔米米': 'Character 1: Mimi the Rabbit',
  '角色1参考图': 'Character 1 Reference',
  '角色2:小狐狸橙橙': 'Character 2: Orange the Fox',
  '主角色2设计图': 'Main Character 2 Design',
  '角色2参考图': 'Character 2 Reference',
  '剧情拆分(16页)': 'Story Breakdown (16 Pages)',
  '16页剧情内容': '16-Page Story Content'
}

export const translateLabel = (label = '') => LABEL_MAP[label] || label
