import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { test } from 'node:test'

const imageNodeSource = readFileSync(new URL('./ImageNode.vue', import.meta.url), 'utf8')
const nodeBaseSource = readFileSync(new URL('./node-base.css', import.meta.url), 'utf8')
const sharedBindingStatusSource = readFileSync(new URL('./NodeBindingStatus.vue', import.meta.url), 'utf8')

function readImageComponentSource(name) {
  const url = new URL(`./image/${name}.vue`, import.meta.url)
  const path = fileURLToPath(url)
  return existsSync(path) ? readFileSync(url, 'utf8') : ''
}

function readImageScriptSource(name) {
  const url = new URL(`./image/${name}.js`, import.meta.url)
  const path = fileURLToPath(url)
  return existsSync(path) ? readFileSync(url, 'utf8') : ''
}

function readUtilitySource(name) {
  const url = new URL(`../../utils/${name}.js`, import.meta.url)
  const path = fileURLToPath(url)
  return existsSync(path) ? readFileSync(url, 'utf8') : ''
}

test('image node delegates passive status and upload progress display to focused components', () => {
  const cropOutputSource = readUtilitySource('imageCropOutput')
  const generationProgressSource = readImageComponentSource('ImageNodeGenerationProgress')
  const progressStateSource = readImageScriptSource('useImageNodeProgressState')
  const uploadProgressSource = readImageComponentSource('ImageNodeUploadProgress')

  assert.match(imageNodeSource, /import NodeBindingStatus from '\.\/NodeBindingStatus\.vue'/)
  assert.match(imageNodeSource, /import ImageNodeGenerationProgress from '\.\/image\/ImageNodeGenerationProgress\.vue'/)
  assert.match(imageNodeSource, /import \{ useImageNodeGeneration \} from '\.\/image\/useImageNodeGeneration\.js'/)
  assert.match(imageNodeSource, /import \{ useImageNodeProgressState \} from '\.\/image\/useImageNodeProgressState\.js'/)
  assert.match(imageNodeSource, /import \{ useImageNodePersistence \} from '\.\/image\/useImageNodePersistence\.js'/)
  assert.match(imageNodeSource, /import \{ useImageNodeReplacement \} from '\.\/image\/useImageNodeReplacement\.js'/)
  assert.match(imageNodeSource, /import ImageNodeUploadProgress from '\.\/image\/ImageNodeUploadProgress\.vue'/)
  assert.match(imageNodeSource, /import \{ createImageNodeCropPayload \} from '@\/utils\/imageCropOutput'/)
  assert.match(imageNodeSource, /import \{ getImageDimensionsFromFile \} from '@\/utils\/imageDimensions'/)
  assert.match(imageNodeSource, /useImageNodeProgressState\(\{/)
  assert.match(imageNodeSource, /useImageNodePersistence\(\{/)
  assert.match(imageNodeSource, /useImageNodeReplacement\(\{/)
  assert.match(imageNodeSource, /useImageNodeGeneration\(\{/)
  assert.match(imageNodeSource, /resetProgress/)
  assert.match(imageNodeSource, /<ImageNodeGenerationProgress\s+v-if="showProgress"\s+:bar-style="progressBarStyle"\s+:percent="progressPercent"\s*\/>/)
  assert.match(imageNodeSource, /<ImageNodeUploadProgress\s+v-if="showUploadProgress"\s+:progress-style="uploadProgressStyle"\s*\/>/)
  assert.match(imageNodeSource, /<NodeBindingStatus\s+:items="imageInputStatusList"\s+:module-style="moduleStyle"\s*\/>/)
  assert.ok(
    imageNodeSource.indexOf('<NodeBindingStatus') > imageNodeSource.indexOf('class="image-node rounded-2xl'),
    'image node status tags should render after the module so shared tag positioning stays consistent'
  )
  assert.doesNotMatch(imageNodeSource, /ImageNodeBindingStatus/)
  assert.doesNotMatch(imageNodeSource, /clearProgressTimers,/)
  assert.doesNotMatch(imageNodeSource, /progressValue,/)
  assert.doesNotMatch(imageNodeSource, /const progressValue = ref\(0\)/)
  assert.doesNotMatch(imageNodeSource, /const progressTimer = ref\(null\)/)
  assert.doesNotMatch(imageNodeSource, /const progressFinishTimer = ref\(null\)/)
  assert.doesNotMatch(imageNodeSource, /const clearProgressTimers = \(\) =>/)
  assert.doesNotMatch(imageNodeSource, /const startProgress = \(\) =>/)
  assert.doesNotMatch(imageNodeSource, /const finishProgress = \(\) =>/)
  assert.doesNotMatch(imageNodeSource, /const resolveImagePersistence = async/)
  assert.doesNotMatch(imageNodeSource, /const resolveImageSaveFeedback = /)
  assert.doesNotMatch(imageNodeSource, /const showImageToolSaveMessage = /)
  assert.doesNotMatch(imageNodeSource, /const replaceCurrentImageNode = async/)
  assert.doesNotMatch(imageNodeSource, /const runImageGeneration = async/)
  assert.doesNotMatch(imageNodeSource, /const handleStopGeneration = \(\) =>/)
  assert.doesNotMatch(imageNodeSource, /const getImageDimensions = \(file\) =>/)
  assert.doesNotMatch(imageNodeSource, /const loadImageElement = async \(source\) =>/)
  assert.doesNotMatch(imageNodeSource, /document\.createElement\('canvas'\)/)
  assert.doesNotMatch(imageNodeSource, /canvas\.toBlob/)
  assert.doesNotMatch(imageNodeSource, /watch\(\s*\(\) => props\.data\?\.loading/)
  assert.doesNotMatch(imageNodeSource, /class="module-progress-shell"/)
  assert.doesNotMatch(imageNodeSource, /class="upload-progress-wrap"/)
  assert.doesNotMatch(imageNodeSource, /class="binding-status-wrap"/)
  assert.doesNotMatch(nodeBaseSource, /\.module-progress-/)
  assert.doesNotMatch(nodeBaseSource, /\.binding-status-/)

  assert.match(sharedBindingStatusSource, /v-for="item in items"/)
  assert.match(sharedBindingStatusSource, /binding-status-pill-active/)
  assert.match(sharedBindingStatusSource, /\.binding-status-wrap\s*\{/)
  assert.match(sharedBindingStatusSource, /margin-top:\s*10px;/)
  assert.match(sharedBindingStatusSource, /justify-content:\s*center;/)
  assert.match(sharedBindingStatusSource, /font-size:\s*12px;/)
  assert.match(generationProgressSource, /defineProps\(\{\s*barStyle:/s)
  assert.match(generationProgressSource, /Generating image\.\.\. \{\{ percent \}\}%/)
  assert.match(generationProgressSource, /\.module-progress-shell\s*\{/)
  assert.match(progressStateSource, /import \{ computed, getCurrentInstance, onUnmounted, ref, watch \} from 'vue'/)
  assert.match(progressStateSource, /export const useImageNodeProgressState = \(/)
  assert.match(progressStateSource, /const clearProgressTimers = \(\) =>/)
  assert.match(progressStateSource, /const startProgress = \(\) =>/)
  assert.match(progressStateSource, /const finishProgress = \(\) =>/)
  assert.match(progressStateSource, /const resetProgress = \(\) =>/)
  assert.match(progressStateSource, /watch\(loading,/)
  assert.match(uploadProgressSource, /defineProps\(\{\s*progressStyle:/s)
  assert.match(uploadProgressSource, /:style="progressStyle"/)
  assert.match(uploadProgressSource, /\.upload-progress-wrap\s*\{/)
  assert.match(cropOutputSource, /import \{ loadImageElementFromSource \} from '\.\/imageElementLoader\.js'/)
  assert.match(cropOutputSource, /export const createImageNodeCropPayload = async/)
  assert.match(cropOutputSource, /canvas\.toBlob/)
})

test('image node delegates image preview modal shell to a focused component', () => {
  const previewDownloadSource = readImageScriptSource('useImageNodePreviewDownload')
  const previewModalSource = readImageComponentSource('ImageNodePreviewModal')
  const previewStateSource = readImageScriptSource('useImageNodePreviewState')

  assert.match(imageNodeSource, /import ImageNodePreviewModal from '\.\/image\/ImageNodePreviewModal\.vue'/)
  assert.match(imageNodeSource, /import \{ useImageNodePreviewDownload \} from '\.\/image\/useImageNodePreviewDownload\.js'/)
  assert.match(imageNodeSource, /import \{\s*PREVIEW_MAX_ZOOM,\s*PREVIEW_MIN_ZOOM,\s*useImageNodePreviewState\s*\} from '\.\/image\/useImageNodePreviewState\.js'/s)
  assert.match(imageNodeSource, /useImageNodePreviewDownload\(\{/)
  assert.match(imageNodeSource, /useImageNodePreviewState\(\{/)
  assert.match(imageNodeSource, /<ImageNodePreviewModal\s+ref="previewModalRef"\s+v-model:show="showPreviewModal"/)
  assert.match(imageNodeSource, /:image-url="displayImageUrl"/)
  assert.match(imageNodeSource, /:preview-zoom="previewZoom"/)
  assert.match(imageNodeSource, /:canvas-style="previewCanvasStyle"/)
  assert.match(imageNodeSource, /:image-style="previewImageStyle"/)
  assert.match(imageNodeSource, /@download="downloadPreviewImage"/)
  assert.match(imageNodeSource, /@image-load="handlePreviewImageLoad"/)
  assert.doesNotMatch(imageNodeSource, /<n-modal/)
  assert.doesNotMatch(imageNodeSource, /class="zoom-modal-card"/)
  assert.doesNotMatch(imageNodeSource, /ref="previewStageRef"/)
  assert.doesNotMatch(imageNodeSource, /NModal/)
  assert.doesNotMatch(imageNodeSource, /DownloadOutline/)
  assert.doesNotMatch(imageNodeSource, /const previewModalRef = ref\(null\)/)
  assert.doesNotMatch(imageNodeSource, /const getPreviewStageElement = \(\) => previewModalRef\.value\?\.getStageElement/)
  assert.doesNotMatch(imageNodeSource, /const previewViewportSize = computed/)
  assert.doesNotMatch(imageNodeSource, /const previewRenderedSize = computed/)
  assert.doesNotMatch(imageNodeSource, /const syncPreviewStageSize = \(\) =>/)
  assert.doesNotMatch(imageNodeSource, /const centerPreviewViewport = \(\) =>/)
  assert.doesNotMatch(imageNodeSource, /const setPreviewZoom = \(nextZoom\) =>/)
  assert.doesNotMatch(imageNodeSource, /const zoomInPreview = \(\) =>/)
  assert.doesNotMatch(imageNodeSource, /const zoomOutPreview = \(\) =>/)
  assert.doesNotMatch(imageNodeSource, /const resetPreviewZoom = \(\) =>/)
  assert.doesNotMatch(imageNodeSource, /const getPreviewDownloadFilename = \(\) =>/)
  assert.doesNotMatch(imageNodeSource, /const triggerPreviewDownload = \(href, filename\) =>/)
  assert.doesNotMatch(imageNodeSource, /const downloadPreviewImage = async \(\) =>/)

  assert.match(previewDownloadSource, /export const getImageNodePreviewDownloadFilename = \(/)
  assert.match(previewDownloadSource, /export const useImageNodePreviewDownload = \(/)
  assert.match(previewDownloadSource, /const downloadPreviewImage = async \(\) =>/)
  assert.match(previewStateSource, /import \{ computed, getCurrentInstance, nextTick, onUnmounted, ref, watch \} from 'vue'/)
  assert.match(previewStateSource, /export const useImageNodePreviewState = \(/)
  assert.match(previewStateSource, /const getPreviewStageElement = \(\) =>/)
  assert.match(previewStateSource, /const previewViewportSize = computed/)
  assert.match(previewStateSource, /const setPreviewZoom = \(nextZoom\) =>/)
  assert.match(previewStateSource, /const setPreviewNaturalSizeFromEvent = \(event\) =>/)

  assert.match(previewModalSource, /import \{ NIcon, NModal \} from 'naive-ui'/)
  assert.match(previewModalSource, /DownloadOutline/)
  assert.match(previewModalSource, /defineEmits\(\['update:show', 'download', 'zoom-out', 'reset-zoom', 'zoom-in', 'image-load'\]\)/)
  assert.match(previewModalSource, /defineExpose\(\{\s*getStageElement\s*\}\)/s)
  assert.match(previewModalSource, /<n-modal\s+:show="show"\s+:mask-closable="true"/)
  assert.match(previewModalSource, /ref="stageRef"/)
  assert.match(previewModalSource, /class="zoom-modal-card"/)
  assert.match(previewModalSource, /\.zoom-modal-card\s*\{/)
})

test('image node delegates crop overlay shell to a focused component', () => {
  const cropInteractionSource = readImageScriptSource('useImageNodeCropInteraction')
  const cropOverlaySource = readImageComponentSource('ImageNodeCropOverlay')
  const displayFrameSource = readImageComponentSource('ImageNodeDisplayFrame')

  assert.match(imageNodeSource, /import \{ useImageNodeCropInteraction \} from '\.\/image\/useImageNodeCropInteraction\.js'/)
  assert.match(imageNodeSource, /useImageNodeCropInteraction\(\{/)
  assert.match(displayFrameSource, /import ImageNodeCropOverlay from '\.\/ImageNodeCropOverlay\.vue'/)
  assert.match(displayFrameSource, /<ImageNodeCropOverlay\s+v-if="cropActive"/)
  assert.match(displayFrameSource, /:mask-styles="cropMaskStyles"/)
  assert.match(displayFrameSource, /:box-style="cropBoxStyle"/)
  assert.match(displayFrameSource, /:handles="cropHandles"/)
  assert.match(displayFrameSource, /@drag-start="\$emit\('crop-drag-start', \$event\)"/)
  assert.match(displayFrameSource, /@resize-start="\s*\(handle, event\) => \$emit\('crop-resize-start', handle, event\)\s*"/s)
  assert.doesNotMatch(imageNodeSource, /ImageNodeCropOverlay/)
  assert.doesNotMatch(imageNodeSource, /class="crop-overlay/)
  assert.doesNotMatch(imageNodeSource, /cropMaskTopStyle|cropMaskLeftStyle|cropMaskRightStyle|cropMaskBottomStyle/)
  assert.doesNotMatch(imageNodeSource, /const activeTool = ref\(''\)/)
  assert.doesNotMatch(imageNodeSource, /const cropRect = ref\(\{ x: 0, y: 0, width: 0, height: 0 \}\)/)
  assert.doesNotMatch(imageNodeSource, /const cropInteraction = ref\(null\)/)
  assert.doesNotMatch(imageNodeSource, /const cropStageMetrics = computed\(\(\) => getImageNodeCropStageMetrics/)
  assert.doesNotMatch(imageNodeSource, /const cropBoxStyle = computed\(\(\) => getImageNodeCropBoxStyle/)
  assert.doesNotMatch(imageNodeSource, /const startCropMode = async \(\) =>/)
  assert.doesNotMatch(imageNodeSource, /const startCropDrag = \(event\) =>/)
  assert.doesNotMatch(imageNodeSource, /const startCropResize = \(handle, event\) =>/)
  assert.doesNotMatch(imageNodeSource, /function onCropPointerMove\(event\)/)
  assert.doesNotMatch(imageNodeSource, /function stopCropInteraction\(\)/)
  assert.doesNotMatch(imageNodeSource, /\.crop-overlay|\.crop-mask|\.crop-box|\.crop-handle|\.crop-inline-tip/)

  assert.match(cropInteractionSource, /import \{ computed, getCurrentInstance, nextTick, onUnmounted, ref, watch \} from 'vue'/)
  assert.match(cropInteractionSource, /export const useImageNodeCropInteraction = \(/)
  assert.match(cropInteractionSource, /const startCropMode = async \(\) =>/)
  assert.match(cropInteractionSource, /const startCropDrag = \(event\) =>/)
  assert.match(cropInteractionSource, /const startCropResize = \(handle, event\) =>/)
  assert.match(cropInteractionSource, /function onCropPointerMove\(event\)/)
  assert.match(cropInteractionSource, /function stopCropInteraction\(\)/)
  assert.match(cropOverlaySource, /defineProps\(\{\s*maskStyles:/s)
  assert.match(cropOverlaySource, /defineEmits\(\['drag-start', 'resize-start'\]\)/)
  assert.match(cropOverlaySource, /class="crop-overlay crop-overlay-inline"/)
  assert.match(cropOverlaySource, /:style="maskStyles\.top"/)
  assert.match(cropOverlaySource, /:style="boxStyle"/)
  assert.match(cropOverlaySource, /v-for="handle in handles"/)
  assert.match(cropOverlaySource, /`crop-handle-\$\{handle\}`/)
  assert.match(cropOverlaySource, /@mousedown\.stop\.prevent="\$emit\('drag-start', \$event\)"/)
  assert.match(cropOverlaySource, /@mousedown\.stop\.prevent="\$emit\('resize-start', handle, \$event\)"/)
  assert.match(cropOverlaySource, /\.crop-overlay\s*\{/)
  assert.match(cropOverlaySource, /\.crop-inline-tip\s*\{/)
})

test('image node delegates base tool action orchestration to a focused composable', () => {
  const toolActionsSource = readImageScriptSource('useImageNodeToolActions')

  assert.match(imageNodeSource, /import \{ useImageNodeToolActions \} from '\.\/image\/useImageNodeToolActions\.js'/)
  assert.match(imageNodeSource, /useImageNodeToolActions\(\{/)
  assert.match(imageNodeSource, /handleToolAction/)
  assert.match(imageNodeSource, /applyCrop/)
  assert.doesNotMatch(imageNodeSource, /const handleToolAction = async/)
  assert.doesNotMatch(imageNodeSource, /const buildEnhancementRequest = \(\) =>/)
  assert.doesNotMatch(imageNodeSource, /const handleEnhanceTo4k = async/)
  assert.doesNotMatch(imageNodeSource, /const handleRemoveBackground = async/)
  assert.doesNotMatch(imageNodeSource, /const applyCrop = async/)

  assert.match(toolActionsSource, /export const useImageNodeToolActions = \(/)
  assert.match(toolActionsSource, /const handleToolAction = async/)
  assert.match(toolActionsSource, /const buildEnhancementRequest = \(\) =>/)
  assert.match(toolActionsSource, /const handleEnhanceTo4k = async/)
  assert.match(toolActionsSource, /const handleRemoveBackground = async/)
  assert.match(toolActionsSource, /const applyCrop = async/)
})

test('image node delegates tool drawer result orchestration to a focused composable', () => {
  const drawerResultsSource = readImageScriptSource('useImageNodeToolDrawerResults')

  assert.match(imageNodeSource, /import \{ useImageNodeToolDrawerResults \} from '\.\/image\/useImageNodeToolDrawerResults\.js'/)
  assert.match(imageNodeSource, /useImageNodeToolDrawerResults\(\{/)
  assert.match(imageNodeSource, /showMultiAngleDrawer/)
  assert.match(imageNodeSource, /showWedding3x3Drawer/)
  assert.match(imageNodeSource, /handleMultiAngleApply/)
  assert.match(imageNodeSource, /handleWedding3x3Apply/)
  assert.doesNotMatch(imageNodeSource, /const pendingMultiAngleNodeId = ref/)
  assert.doesNotMatch(imageNodeSource, /const pendingWedding3x3NodeId = ref/)
  assert.doesNotMatch(imageNodeSource, /const handleMultiAngleApply = async/)
  assert.doesNotMatch(imageNodeSource, /const handleMultiAnglePending = async/)
  assert.doesNotMatch(imageNodeSource, /const handleMultiAngleError = async/)
  assert.doesNotMatch(imageNodeSource, /const handleWedding3x3Apply = async/)
  assert.doesNotMatch(imageNodeSource, /const handleWedding3x3Pending = async/)
  assert.doesNotMatch(imageNodeSource, /const handleWedding3x3Error = async/)

  assert.match(drawerResultsSource, /import \{ ref \} from 'vue'/)
  assert.match(drawerResultsSource, /export const useImageNodeToolDrawerResults = \(/)
  assert.match(drawerResultsSource, /const handleMultiAngleApply = async/)
  assert.match(drawerResultsSource, /const handleMultiAnglePending = async/)
  assert.match(drawerResultsSource, /const handleMultiAngleError = async/)
  assert.match(drawerResultsSource, /const handleWedding3x3Apply = async/)
  assert.match(drawerResultsSource, /const handleWedding3x3Pending = async/)
  assert.match(drawerResultsSource, /const handleWedding3x3Error = async/)
})

test('image node delegates loaded image frame display to a focused component', () => {
  const canvasPreviewSource = readImageScriptSource('useImageNodeCanvasPreview')
  const displayFrameSource = readImageComponentSource('ImageNodeDisplayFrame')

  assert.match(imageNodeSource, /import \{ useImageNodeCanvasPreview \} from '\.\/image\/useImageNodeCanvasPreview\.js'/)
  assert.match(imageNodeSource, /import ImageNodeDisplayFrame from '\.\/image\/ImageNodeDisplayFrame\.vue'/)
  assert.match(imageNodeSource, /useImageNodeCanvasPreview\(\{/)
  assert.match(imageNodeSource, /<ImageNodeDisplayFrame\s+v-else-if="hasDisplayImage"/)
  assert.match(imageNodeSource, /:image-url="canvasDisplayImageUrl"/)
  assert.match(imageNodeSource, /:alt="data\.label \|\| 'Image'"/)
  assert.match(imageNodeSource, /:crop-active="activeTool === 'crop'"/)
  assert.match(imageNodeSource, /:crop-mask-styles="cropMaskStyles"/)
  assert.match(imageNodeSource, /:crop-box-style="cropBoxStyle"/)
  assert.match(imageNodeSource, /:crop-handles="cropHandles"/)
  assert.match(imageNodeSource, /@image-load="handlePreviewImageLoad"/)
  assert.match(imageNodeSource, /@crop-drag-start="startCropDrag"/)
  assert.match(imageNodeSource, /@crop-resize-start="startCropResize"/)
  assert.doesNotMatch(imageNodeSource, /class="module-image/)
  assert.doesNotMatch(imageNodeSource, /\.module-image-/)
  assert.doesNotMatch(imageNodeSource, /const cachedCanvasPreviewUrl = ref\(''\)/)
  assert.doesNotMatch(imageNodeSource, /const canvasPreviewState = ref\('idle'\)/)
  assert.doesNotMatch(imageNodeSource, /let canvasPreviewRequestId = 0/)
  assert.doesNotMatch(imageNodeSource, /let canvasPreviewSource = ''/)
  assert.doesNotMatch(imageNodeSource, /const syncCanvasImagePreview = async \(\) =>/)
  assert.doesNotMatch(imageNodeSource, /watch\(\s*\[\s*displayImageUrl,\s*isCanvasInteracting\s*\]/)

  assert.match(canvasPreviewSource, /import \{ computed, ref, watch \} from 'vue'/)
  assert.match(canvasPreviewSource, /export const useImageNodeCanvasPreview = \(/)
  assert.match(canvasPreviewSource, /const syncCanvasImagePreview = async \(\) =>/)
  assert.match(canvasPreviewSource, /const canvasDisplayImageUrl = computed\(\(\) =>/)
  assert.match(displayFrameSource, /defineProps\(\{\s*imageUrl:/s)
  assert.match(displayFrameSource, /defineEmits\(\['image-load', 'crop-drag-start', 'crop-resize-start'\]\)/)
  assert.match(displayFrameSource, /class="module-image-shell"/)
  assert.match(displayFrameSource, /class="module-image-frame"/)
  assert.match(displayFrameSource, /v-if="imageUrl"/)
  assert.match(displayFrameSource, /:src="imageUrl"/)
  assert.match(displayFrameSource, /:alt="alt"/)
  assert.match(displayFrameSource, /@load="\$emit\('image-load', \$event\)"/)
  assert.match(displayFrameSource, /Preparing preview\.\.\./)
  assert.match(displayFrameSource, /\.module-image-shell\s*\{/)
  assert.match(displayFrameSource, /\.module-image-preview-placeholder\s*\{/)
})

test('image node delegates empty upload prompt to a focused component', () => {
  const emptyStateSource = readImageComponentSource('ImageNodeEmptyState')

  assert.match(imageNodeSource, /import ImageNodeEmptyState from '\.\/image\/ImageNodeEmptyState\.vue'/)
  assert.match(imageNodeSource, /<ImageNodeEmptyState\s+v-else\s+@upload="triggerUpload"\s*\/>/)
  assert.doesNotMatch(imageNodeSource, /Drop an image or click to upload/)
  assert.doesNotMatch(imageNodeSource, /class="upload-btn/)
  assert.doesNotMatch(imageNodeSource, /\.upload-btn\s*\{/)

  assert.match(emptyStateSource, /import \{ NIcon \} from 'naive-ui'/)
  assert.match(emptyStateSource, /import \{ ImageOutline \} from '@\/icons\/coolicons'/)
  assert.match(emptyStateSource, /defineEmits\(\['upload'\]\)/)
  assert.match(emptyStateSource, /class="w-full h-full bg-\[#0f0f0f\] flex flex-col items-center justify-center gap-2 relative text-center px-4 nodrag nopan"/)
  assert.match(emptyStateSource, /@mousedown\.stop/)
  assert.match(emptyStateSource, /<n-icon :size="32" class="text-\[#7b818c\]"><ImageOutline \/><\/n-icon>/)
  assert.match(emptyStateSource, /Drop an image or click to upload/)
  assert.match(emptyStateSource, /class="upload-btn nodrag nopan"/)
  assert.match(emptyStateSource, /@click\.stop="\$emit\('upload'\)"/)
  assert.match(emptyStateSource, /\.upload-btn\s*\{/)
})

test('image node delegates URL loading placeholder to a focused component', () => {
  const loadingStateSource = readImageComponentSource('ImageNodeLoadingState')

  assert.match(imageNodeSource, /import ImageNodeLoadingState from '\.\/image\/ImageNodeLoadingState\.vue'/)
  assert.match(imageNodeSource, /<ImageNodeLoadingState\s+v-else-if="urlLoading"\s*\/>/)
  assert.doesNotMatch(imageNodeSource, /Loading\.\.\./)
  assert.doesNotMatch(imageNodeSource, /alt="Loading"/)
  assert.doesNotMatch(imageNodeSource, /src="\.\.\/\.\.\/assets\/loading\.webp"/)

  assert.match(loadingStateSource, /class="w-full h-full bg-\[#1a1c21\] flex flex-col items-center justify-center gap-3"/)
  assert.match(loadingStateSource, /src="\.\.\/\.\.\/\.\.\/assets\/loading\.webp"/)
  assert.match(loadingStateSource, /alt="Loading"/)
  assert.match(loadingStateSource, /class="w-14 h-12"/)
  assert.match(loadingStateSource, /Loading\.\.\./)
})

test('image node delegates feedback modals to a focused component', () => {
  const feedbackModalsSource = readImageComponentSource('ImageNodeFeedbackModals')

  assert.match(imageNodeSource, /import ImageNodeFeedbackModals from '\.\/image\/ImageNodeFeedbackModals\.vue'/)
  assert.match(
    imageNodeSource,
    /<ImageNodeFeedbackModals\s+v-model:show-error="showErrorModal"\s+v-model:show-validation="showValidationModal"\s+:error-message="data\.error"\s+:validation-message="validationMessage"\s+@close-error="closeErrorModal"\s+@close-validation="closeValidationModal"\s*\/>/
  )
  assert.doesNotMatch(imageNodeSource, /<BaseModal/)
  assert.doesNotMatch(imageNodeSource, /BaseButton|BaseModalActions|BaseModalCopy/)

  assert.match(feedbackModalsSource, /import \{ BaseButton, BaseModal, BaseModalActions, BaseModalCopy \} from '@\/components\/ui'/)
  assert.match(feedbackModalsSource, /defineProps\(\{\s*showError:/s)
  assert.match(feedbackModalsSource, /defineEmits\(\['update:showError', 'update:showValidation', 'closeError', 'closeValidation'\]\)/)
  assert.match(feedbackModalsSource, /<BaseModal\s+:show="showError"/)
  assert.match(feedbackModalsSource, /title="Image Module Error"/)
  assert.match(feedbackModalsSource, /@update:show="\$emit\('update:showError', \$event\)"/)
  assert.match(feedbackModalsSource, /<BaseModalCopy class="whitespace-pre-wrap">\{\{ errorMessage \}\}<\/BaseModalCopy>/)
  assert.match(feedbackModalsSource, /<BaseButton @click="\$emit\('closeError'\)">Close<\/BaseButton>/)
  assert.match(feedbackModalsSource, /:show="showValidation"/)
  assert.match(feedbackModalsSource, /title="Upload Limit"/)
  assert.match(feedbackModalsSource, /@update:show="\$emit\('update:showValidation', \$event\)"/)
  assert.match(feedbackModalsSource, /<BaseModalCopy class="whitespace-pre-wrap">\{\{ validationMessage \}\}<\/BaseModalCopy>/)
  assert.match(feedbackModalsSource, /<BaseButton @click="\$emit\('closeValidation'\)">OK<\/BaseButton>/)
  assert.match(imageNodeSource, /props\.data\?\.suppressErrorModal/)
})

test('image node delegates capsule toolbar to a focused component', () => {
  const capsuleMenuSource = readImageComponentSource('ImageNodeCapsuleMenu')

  assert.match(imageNodeSource, /import ImageNodeCapsuleMenu from '\.\/image\/ImageNodeCapsuleMenu\.vue'/)
  assert.match(imageNodeSource, /<ImageNodeCapsuleMenu\s+v-show="showNodeCapsule"/)
  assert.match(imageNodeSource, /:capsule-style="capsuleStyle"/)
  assert.match(imageNodeSource, /:image-model-options="imageModelDropdownOptions"/)
  assert.match(imageNodeSource, /:tool-options="toolDropdownOptions"/)
  assert.match(imageNodeSource, /@select-model="setImageModel"/)
  assert.match(imageNodeSource, /@tool-action="handleToolAction"/)
  assert.match(imageNodeSource, /@create="handleGenerateImage"/)
  assert.match(imageNodeSource, /@stop="handleStopGeneration"/)
  assert.doesNotMatch(imageNodeSource, /<BaseDropdown/)
  assert.doesNotMatch(imageNodeSource, /class="capsule-menu/)
  assert.doesNotMatch(imageNodeSource, /createIcon|toolsIcon|CloseCircleOutline|CopyOutline|ExpandOutline|RefreshOutline|TrashOutline/)
  assert.doesNotMatch(imageNodeSource, /\.capsule-tool-trigger|\.capsule-tool-icon/)

  assert.match(capsuleMenuSource, /import \{ NIcon \} from 'naive-ui'/)
  assert.match(capsuleMenuSource, /import \{ BaseDropdown \} from '@\/components\/ui'/)
  assert.match(capsuleMenuSource, /import createIcon from '@\/assets\/create-icon\.svg'/)
  assert.match(capsuleMenuSource, /import toolsIcon from '@\/assets\/tools-icon\.svg'/)
  assert.match(capsuleMenuSource, /defineEmits\(\[\s*'selectModel'/s)
  assert.match(capsuleMenuSource, /class="capsule-menu absolute left-1\/2 z-\[1200\]"/)
  assert.match(capsuleMenuSource, /<BaseDropdown :options="imageModelOptions" compact @select="\$emit\('selectModel', \$event\)"/)
  assert.match(capsuleMenuSource, /<BaseDropdown :options="toolOptions" compact @select="\$emit\('toolAction', \$event\)"/)
  assert.match(capsuleMenuSource, /@click="\$emit\('preview'\)"/)
  assert.match(capsuleMenuSource, /@click="\$emit\('duplicate'\)"/)
  assert.match(capsuleMenuSource, /@click="\$emit\('delete'\)"/)
  assert.match(capsuleMenuSource, /@click="\$emit\('create'\)"/)
  assert.match(capsuleMenuSource, /@click="\$emit\('regenerate'\)"/)
  assert.match(capsuleMenuSource, /@click="\$emit\('stop'\)"/)
  assert.match(capsuleMenuSource, /<style scoped src="\.\/\.\.\/node-base\.css"><\/style>/)
  assert.match(capsuleMenuSource, /\.capsule-tool-trigger\s*\{/)
  assert.match(capsuleMenuSource, /\.capsule-tool-icon\s*\{/)
})

test('image node delegates image tool drawers to a focused component', () => {
  const toolDrawersSource = readImageComponentSource('ImageNodeToolDrawers')

  assert.match(imageNodeSource, /import ImageNodeToolDrawers from '\.\/image\/ImageNodeToolDrawers\.vue'/)
  assert.match(imageNodeSource, /<ImageNodeToolDrawers\s+v-model:show-multi-angle="showMultiAngleDrawer"\s+v-model:show-wedding3x3="showWedding3x3Drawer"/)
  assert.match(imageNodeSource, /:image-url="displayImageUrl"/)
  assert.match(imageNodeSource, /:model="localImageModel"/)
  assert.match(imageNodeSource, /:ratio-options="ratioDropdownOptions"/)
  assert.match(imageNodeSource, /:size-options="imageSizeOptions"/)
  assert.match(imageNodeSource, /@multi-angle-pending="handleMultiAnglePending"/)
  assert.match(imageNodeSource, /@multi-angle-apply="handleMultiAngleApply"/)
  assert.match(imageNodeSource, /@wedding3x3-apply="handleWedding3x3Apply"/)
  assert.doesNotMatch(imageNodeSource, /import MultiAngleToolDrawer from '@\/components\/tools\/MultiAngleToolDrawer\.vue'/)
  assert.doesNotMatch(imageNodeSource, /import Wedding3x3ToolDrawer from '@\/components\/tools\/Wedding3x3ToolDrawer\.vue'/)
  assert.doesNotMatch(imageNodeSource, /<MultiAngleToolDrawer/)
  assert.doesNotMatch(imageNodeSource, /<Wedding3x3ToolDrawer/)

  assert.match(toolDrawersSource, /import MultiAngleToolDrawer from '@\/components\/tools\/MultiAngleToolDrawer\.vue'/)
  assert.match(toolDrawersSource, /import Wedding3x3ToolDrawer from '@\/components\/tools\/Wedding3x3ToolDrawer\.vue'/)
  assert.match(toolDrawersSource, /defineProps\(\{\s*showMultiAngle:/s)
  assert.match(toolDrawersSource, /defineEmits\(\[\s*'update:showMultiAngle'/s)
  assert.match(toolDrawersSource, /<MultiAngleToolDrawer\s+:show="showMultiAngle"/)
  assert.match(toolDrawersSource, /@update:show="\$emit\('update:showMultiAngle', \$event\)"/)
  assert.match(toolDrawersSource, /@pending="\$emit\('multiAnglePending', \$event\)"/)
  assert.match(toolDrawersSource, /@apply="\$emit\('multiAngleApply', \$event\)"/)
  assert.match(toolDrawersSource, /@error="\$emit\('multiAngleError', \$event\)"/)
  assert.match(toolDrawersSource, /<Wedding3x3ToolDrawer\s+:show="showWedding3x3"/)
  assert.match(toolDrawersSource, /:quality="quality"/)
  assert.match(toolDrawersSource, /@update:show="\$emit\('update:showWedding3x3', \$event\)"/)
  assert.match(toolDrawersSource, /@pending="\$emit\('wedding3x3Pending', \$event\)"/)
  assert.match(toolDrawersSource, /@apply="\$emit\('wedding3x3Apply', \$event\)"/)
  assert.match(toolDrawersSource, /@error="\$emit\('wedding3x3Error', \$event\)"/)
})

test('image node delegates model and size capsule state to a focused composable', () => {
  const modelControlsSource = readImageScriptSource('useImageNodeModelControls')

  assert.match(imageNodeSource, /import \{ useImageNodeModelControls \} from '\.\/image\/useImageNodeModelControls\.js'/)
  assert.match(imageNodeSource, /useImageNodeModelControls\(\{/)
  assert.match(imageNodeSource, /buildModelParamsPatch:\s*getImageNodeModelParamsPatch/)
  assert.match(imageNodeSource, /buildSizeParamsPatch:\s*getImageNodeSizeParamsPatch/)
  assert.match(imageNodeSource, /defaultImageModel:\s*DEFAULT_IMAGE_MODEL/)
  assert.match(imageNodeSource, /defaultImageSize:\s*DEFAULT_IMAGE_SIZE/)
  assert.match(imageNodeSource, /nodeId:\s*\(\) => props\.id/)
  assert.match(imageNodeSource, /stageStyle\s*\}/)
  assert.doesNotMatch(imageNodeSource, /const localImageModel = ref/)
  assert.doesNotMatch(imageNodeSource, /const localImageSize = ref/)
  assert.doesNotMatch(imageNodeSource, /const localImageQuality = ref/)
  assert.doesNotMatch(imageNodeSource, /const localBackground = ref/)
  assert.doesNotMatch(imageNodeSource, /const localOutputFormat = ref/)
  assert.doesNotMatch(imageNodeSource, /const GPT_IMAGE_2_RATIO_OPTIONS = \[/)
  assert.doesNotMatch(imageNodeSource, /const imageModelDropdownOptions = computed/)
  assert.doesNotMatch(imageNodeSource, /const stageStyle = computed/)
  assert.doesNotMatch(imageNodeSource, /const pickNearestSizeKey = \(ratioKey, resolutionKey\) =>/)
  assert.doesNotMatch(imageNodeSource, /const findNearestSizeKey = \(ratioKey, resolutionKey\) =>/)
  assert.doesNotMatch(imageNodeSource, /const setImageModel = \(key\) =>/)
  assert.doesNotMatch(imageNodeSource, /const setImageRatio = \(ratioKey\) =>/)
  assert.doesNotMatch(imageNodeSource, /getImageNodeSizeSelection/)
  assert.doesNotMatch(imageNodeSource, /getImageNodeNearestSizeKey/)

  assert.match(modelControlsSource, /export const GPT_IMAGE_2_RATIO_OPTIONS = \[/)
  assert.match(modelControlsSource, /export const useImageNodeModelControls = \(/)
  assert.match(modelControlsSource, /const imageModelDropdownOptions = computed/)
  assert.match(modelControlsSource, /const pickNearestSizeKey = \(ratioKey, resolutionKey\) =>/)
  assert.match(modelControlsSource, /const findNearestSizeKey = \(ratioKey, resolutionKey\) =>/)
  assert.match(modelControlsSource, /const setImageModel = \(key\) =>/)
  assert.match(modelControlsSource, /return \{\s*backgroundDropdownOptions,/s)
})

test('image node delegates upload lifecycle side effects to a focused composable', () => {
  const uploadLifecycleSource = readImageScriptSource('useImageNodeUploadLifecycle')

  assert.match(imageNodeSource, /import \{ useImageNodeUploadLifecycle \} from '\.\/image\/useImageNodeUploadLifecycle\.js'/)
  assert.match(imageNodeSource, /useImageNodeUploadLifecycle\(\{/)
  assert.match(imageNodeSource, /uploadInputRef,/)
  assert.match(imageNodeSource, /showUploadProgress,/)
  assert.match(imageNodeSource, /uploadProgress,/)
  assert.match(imageNodeSource, /uploadStage/)
  assert.match(imageNodeSource, /stopCropInteraction\(\)/)
  assert.doesNotMatch(imageNodeSource, /const localPreviewUrl = ref\(''\)/)
  assert.doesNotMatch(imageNodeSource, /const isBlobUrl = \(value\) =>/)
  assert.doesNotMatch(imageNodeSource, /const revokeBlobUrl = \(value\) =>/)
  assert.doesNotMatch(imageNodeSource, /const clearLocalPreviewUrl = \(\) =>/)
  assert.doesNotMatch(imageNodeSource, /const replaceLocalPreviewUrl = \(nextUrl = ''\) =>/)
  assert.doesNotMatch(imageNodeSource, /const beforeUnloadGuard = \(event\) =>/)
  assert.doesNotMatch(imageNodeSource, /watch\(isUploading,/)
  assert.doesNotMatch(imageNodeSource, /window\.addEventListener\('beforeunload'/)
  assert.doesNotMatch(imageNodeSource, /window\.removeEventListener\('beforeunload'/)
  assert.doesNotMatch(imageNodeSource, /const resetUploadProgress = \(delayMs = 1500\) =>/)
  assert.doesNotMatch(imageNodeSource, /const triggerUpload = \(\) =>/)
  assert.doesNotMatch(imageNodeSource, /const applyUploadSaveOutcome = \(outcome = \{\}\) =>/)

  assert.match(uploadLifecycleSource, /export const useImageNodeUploadLifecycle = \(/)
  assert.match(uploadLifecycleSource, /const beforeUnloadGuard = \(event\) =>/)
  assert.match(uploadLifecycleSource, /watch\(isUploading,/)
  assert.match(uploadLifecycleSource, /const replaceLocalPreviewUrl = \(nextUrl = ''\) =>/)
  assert.match(uploadLifecycleSource, /const clearLocalPreviewUrl = \(\) =>/)
  assert.match(uploadLifecycleSource, /const resetUploadProgress = \(delayMs = 1500\) =>/)
  assert.match(uploadLifecycleSource, /const applyUploadSaveOutcome = \(outcome = \{\}\) =>/)
  assert.match(uploadLifecycleSource, /const triggerUpload = \(\) =>/)
})

test('image node delegates upload persistence orchestration to a focused composable', () => {
  const uploadPersistenceSource = readImageScriptSource('useImageNodeUploadPersistence')

  assert.match(imageNodeSource, /import \{ useImageNodeUploadPersistence \} from '\.\/image\/useImageNodeUploadPersistence\.js'/)
  assert.match(imageNodeSource, /useImageNodeUploadPersistence\(\{/)
  assert.match(imageNodeSource, /handleFileUpload/)
  assert.doesNotMatch(imageNodeSource, /const handleFileUpload = async/)
  assert.doesNotMatch(imageNodeSource, /file\.size > MAX_UPLOAD_SIZE_BYTES/)
  assert.doesNotMatch(imageNodeSource, /getImageDimensionsFromFile\(file\)/)
  assert.doesNotMatch(imageNodeSource, /URL\.createObjectURL\(file\)/)
  assert.doesNotMatch(imageNodeSource, /uploadImageFile\(file,/)
  assert.doesNotMatch(imageNodeSource, /updateNode\(props\.id, getImageNodeUploadFailurePatch\(\)\)/)

  assert.match(uploadPersistenceSource, /export const useImageNodeUploadPersistence = \(/)
  assert.match(uploadPersistenceSource, /const handleFileUpload = async/)
  assert.match(uploadPersistenceSource, /getImageDimensionsFromFile\(file\)/)
  assert.match(uploadPersistenceSource, /createObjectURL\(file\)/)
  assert.match(uploadPersistenceSource, /uploadImageFile\(file,/)
  assert.match(uploadPersistenceSource, /getImageNodeUploadFailurePatch/)
})

test('image node delegates linked image node orchestration to a focused composable', () => {
  const linkedNodesSource = readImageScriptSource('useImageNodeLinkedNodes')

  assert.match(imageNodeSource, /import \{ useImageNodeLinkedNodes \} from '\.\/image\/useImageNodeLinkedNodes\.js'/)
  assert.match(imageNodeSource, /useImageNodeLinkedNodes\(\{/)
  assert.match(imageNodeSource, /buildCreateData:\s*getImageNodeLinkedCreateData/)
  assert.match(imageNodeSource, /buildUpdatePatch:\s*getImageNodeLinkedUpdatePatch/)
  assert.match(imageNodeSource, /buildPosition:\s*getImageNodeLinkedPosition/)
  assert.match(imageNodeSource, /buildSelectionState:\s*getImageNodeLinkedSelectionState/)
  assert.match(imageNodeSource, /getDefaults:\s*\(\) => \(\{/)
  assert.match(imageNodeSource, /stageStyle:\s*\(\) => stageStyle\.value/)
  assert.doesNotMatch(imageNodeSource, /const createLinkedImageNode = \(payload = \{\}\) =>/)
  assert.doesNotMatch(imageNodeSource, /const updateLinkedImageNode = async \(nodeId, payload = \{\}\) =>/)
  assert.doesNotMatch(imageNodeSource, /nodes\.value = getImageNodeLinkedSelectionState/)
  assert.doesNotMatch(imageNodeSource, /addEdge\(edgeStrategy\.resolve/)
  assert.doesNotMatch(imageNodeSource, /setTimeout\(\(\) => \{\s*updateNodeInternals\(props\.id\)/s)

  assert.match(linkedNodesSource, /export const useImageNodeLinkedNodes = \(/)
  assert.match(linkedNodesSource, /getCanvasAutoPlacementPosition/)
  assert.match(linkedNodesSource, /const createData = buildCreateData\(\{/)
  assert.match(linkedNodesSource, /const placedPosition = getCanvasAutoPlacementPosition\(\{/)
  assert.match(linkedNodesSource, /existingNodes: readNodes\(\)/)
  assert.match(linkedNodesSource, /const createLinkedImageNode = \(payload = \{\}\) =>/)
  assert.match(linkedNodesSource, /const updateLinkedImageNode = async \(linkedNodeId, payload = \{\}\) =>/)
  assert.match(linkedNodesSource, /addEdge\(resolveEdge\(\{/)
  assert.match(linkedNodesSource, /setNodes\(buildSelectionState\(\{/)
  assert.match(linkedNodesSource, /return \{\s*createLinkedImageNode,\s*updateLinkedImageNode\s*\}/s)
})
