import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { test } from 'node:test'

const videoNodeSource = readFileSync(new URL('./VideoNode.vue', import.meta.url), 'utf8')
const sharedBindingStatusSource = readFileSync(new URL('./NodeBindingStatus.vue', import.meta.url), 'utf8')

function readVideoComponentSource(name) {
  const url = new URL(`./video/${name}.vue`, import.meta.url)
  const path = fileURLToPath(url)
  return existsSync(path) ? readFileSync(url, 'utf8') : ''
}

function readVideoScriptSource(name) {
  const url = new URL(`./video/${name}.js`, import.meta.url)
  const path = fileURLToPath(url)
  return existsSync(path) ? readFileSync(url, 'utf8') : ''
}

test('video node delegates passive status and progress display to focused components', () => {
  const generationProgressSource = readVideoComponentSource('VideoNodeGenerationProgress')
  const uploadProgressSource = readVideoComponentSource('VideoNodeUploadProgress')
  const progressStateSource = readVideoScriptSource('useVideoNodeProgressState')

  assert.match(videoNodeSource, /import NodeBindingStatus from '\.\/NodeBindingStatus\.vue'/)
  assert.match(videoNodeSource, /import VideoNodeGenerationProgress from '\.\/video\/VideoNodeGenerationProgress\.vue'/)
  assert.match(videoNodeSource, /import VideoNodeUploadProgress from '\.\/video\/VideoNodeUploadProgress\.vue'/)
  assert.match(videoNodeSource, /import \{ useVideoNodeProgressState \} from '\.\/video\/useVideoNodeProgressState\.js'/)
  assert.match(videoNodeSource, /<VideoNodeGenerationProgress\s+v-if="showProgress"\s+:bar-style="progressBarStyle"\s+:percent="progressPercent"\s*\/>/)
  assert.match(videoNodeSource, /<VideoNodeUploadProgress\s+v-if="showUploadProgress"\s+:module-style="moduleStyle"\s+:progress-style="uploadProgressStyle"\s*\/>/)
  assert.match(videoNodeSource, /<NodeBindingStatus\s+:module-style="moduleStyle"\s+:items="imageRoleStatusList"\s*\/>/)
  assert.doesNotMatch(videoNodeSource, /<NodeBindingStatus[\s\S]*\sflush\s*\/>/)
  assert.match(videoNodeSource, /useVideoNodeProgressState\(\{\s*error:/s)
  assert.match(videoNodeSource, /hasVideo: \(\) => !!props\.data\?\.url/)
  assert.match(videoNodeSource, /resetProgress/)
  assert.doesNotMatch(videoNodeSource, /VideoNodeBindingStatus/)
  assert.doesNotMatch(videoNodeSource, /class="module-progress-shell"/)
  assert.doesNotMatch(videoNodeSource, /class="upload-progress-wrap"/)
  assert.doesNotMatch(videoNodeSource, /class="binding-status-wrap"/)
  assert.doesNotMatch(videoNodeSource, /const progressValue = ref\(0\)/)
  assert.doesNotMatch(videoNodeSource, /const showProgress = ref\(false\)/)
  assert.doesNotMatch(videoNodeSource, /const progressTimer = ref\(null\)/)
  assert.doesNotMatch(videoNodeSource, /const progressFinishTimer = ref\(null\)/)
  assert.doesNotMatch(videoNodeSource, /const clearProgressTimers = \(\) =>/)
  assert.doesNotMatch(videoNodeSource, /const startProgress = \(\) =>/)
  assert.doesNotMatch(videoNodeSource, /const finishProgress = \(\) =>/)
  assert.doesNotMatch(videoNodeSource, /\.upload-progress-wrap\s*\{/)
  assert.doesNotMatch(videoNodeSource, /\.upload-progress-track\s*\{/)
  assert.doesNotMatch(videoNodeSource, /\.upload-progress-bar\s*\{/)

  assert.match(sharedBindingStatusSource, /defineProps\(\{\s*moduleStyle:/s)
  assert.match(sharedBindingStatusSource, /items:/)
  assert.match(sharedBindingStatusSource, /flush:/)
  assert.match(sharedBindingStatusSource, /v-for="item in items"/)
  assert.match(sharedBindingStatusSource, /binding-status-pill-active/)
  assert.match(sharedBindingStatusSource, /\.binding-status-wrap\s*\{/)
  assert.match(sharedBindingStatusSource, /margin-top:\s*10px;/)
  assert.match(generationProgressSource, /defineProps\(\{\s*barStyle:/s)
  assert.match(generationProgressSource, /Generating video\.\.\. \{\{ percent \}\}%/)
  assert.match(generationProgressSource, /\.module-progress-shell\s*\{/)
  assert.match(progressStateSource, /import \{ computed, getCurrentInstance, onUnmounted, ref, watch \} from 'vue'/)
  assert.match(progressStateSource, /export const useVideoNodeProgressState = \(/)
  assert.match(progressStateSource, /const clearProgressTimers = \(\) =>/)
  assert.match(progressStateSource, /const startProgress = \(\) =>/)
  assert.match(progressStateSource, /const finishProgress = \(\) =>/)
  assert.match(progressStateSource, /const resetProgress = \(\) =>/)
  assert.match(progressStateSource, /watch\(\s*loading,/)
  assert.match(uploadProgressSource, /defineProps\(\{\s*moduleStyle:/s)
  assert.match(uploadProgressSource, /progressStyle:/)
  assert.match(uploadProgressSource, /:style="progressStyle"/)
  assert.match(uploadProgressSource, /\.upload-progress-wrap\s*\{/)
})

test('video node delegates loaded video frame display to a focused component', () => {
  const displayFrameSource = readVideoComponentSource('VideoNodeDisplayFrame')

  assert.match(videoNodeSource, /import VideoNodeDisplayFrame from '\.\/video\/VideoNodeDisplayFrame\.vue'/)
  assert.match(videoNodeSource, /<VideoNodeDisplayFrame\s+v-else-if="displayVideoUrl && !data\.loading"/)
  assert.match(videoNodeSource, /:video-url="displayVideoUrl"/)
  assert.match(videoNodeSource, /:is-interactive="isVideoInteractive"/)
  assert.match(videoNodeSource, /:show-static-preview="showStaticVideoPreview"/)
  assert.match(videoNodeSource, /@activate-preview="activateInlineVideoPreview"/)
  assert.doesNotMatch(videoNodeSource, /class="module-video/)
  assert.doesNotMatch(videoNodeSource, /\.module-video/)

  assert.match(displayFrameSource, /import \{ NIcon \} from 'naive-ui'/)
  assert.match(displayFrameSource, /import \{ VideocamOutline \} from '@\/icons\/coolicons'/)
  assert.match(displayFrameSource, /defineProps\(\{\s*videoUrl:/s)
  assert.match(displayFrameSource, /isInteractive:/)
  assert.match(displayFrameSource, /showStaticPreview:/)
  assert.match(displayFrameSource, /defineEmits\(\['activatePreview'\]\)/)
  assert.match(displayFrameSource, /class="module-video-shell"/)
  assert.match(displayFrameSource, /class="module-video-frame"/)
  assert.match(displayFrameSource, /v-if="isInteractive"/)
  assert.match(displayFrameSource, /:src="videoUrl"/)
  assert.match(displayFrameSource, /class="module-video"/)
  assert.match(displayFrameSource, /v-else-if="showStaticPreview"/)
  assert.match(displayFrameSource, /@click="\$emit\('activatePreview'\)"/)
  assert.match(displayFrameSource, /class="module-video-static-media"/)
  assert.match(displayFrameSource, /Preview video/)
  assert.match(displayFrameSource, /\.module-video-shell\s*\{/)
  assert.match(displayFrameSource, /\.module-video-static-preview\s*\{/)
})

test('video node delegates empty upload prompt to a focused component', () => {
  const emptyStateSource = readVideoComponentSource('VideoNodeEmptyState')

  assert.match(videoNodeSource, /import VideoNodeEmptyState from '\.\/video\/VideoNodeEmptyState\.vue'/)
  assert.match(videoNodeSource, /<template v-else>\s*<VideoNodeEmptyState/s)
  assert.match(videoNodeSource, /:show-previews="activeImageRoleSet\.keys\.size > 0"/)
  assert.match(videoNodeSource, /:items="imageRoleStatusList"/)
  assert.match(videoNodeSource, /:connect-hint="connectHint"/)
  assert.match(videoNodeSource, /@upload="triggerUpload"/)
  assert.match(videoNodeSource, /<input ref="uploadInputRef" type="file" accept="video\/\*" class="hidden" @change="handleFileUpload" \/>/)
  assert.doesNotMatch(videoNodeSource, /imageRoleStatusList\.filter/)
  assert.doesNotMatch(videoNodeSource, /<button class="upload-btn" @click="triggerUpload">Upload<\/button>/)
  assert.doesNotMatch(videoNodeSource, /<n-icon :size="32" class="text-\[#7b818c\]"><VideocamOutline \/><\/n-icon>/)

  assert.match(emptyStateSource, /import \{ NIcon \} from 'naive-ui'/)
  assert.match(emptyStateSource, /import \{ VideocamOutline \} from '@\/icons\/coolicons'/)
  assert.match(emptyStateSource, /defineProps\(\{\s*showPreviews:/s)
  assert.match(emptyStateSource, /items:/)
  assert.match(emptyStateSource, /connectHint:/)
  assert.match(emptyStateSource, /defineEmits\(\['upload'\]\)/)
  assert.match(emptyStateSource, /v-if="showPreviews"/)
  assert.match(emptyStateSource, /v-for="item in visiblePreviewItems"/)
  assert.match(emptyStateSource, /item\.active && item\.previewUrl/)
  assert.match(emptyStateSource, /:src="item\.previewUrl"/)
  assert.match(emptyStateSource, /\{\{ item\.label \}\}/)
  assert.match(emptyStateSource, /\{\{ connectHint \}\}/)
  assert.match(emptyStateSource, /<button class="upload-btn" @click="\$emit\('upload'\)">Upload<\/button>/)
})

test('video node delegates preview and feedback modals to focused components', () => {
  const previewModalSource = readVideoComponentSource('VideoNodePreviewModal')
  const feedbackModalsSource = readVideoComponentSource('VideoNodeFeedbackModals')

  assert.match(videoNodeSource, /import VideoNodePreviewModal from '\.\/video\/VideoNodePreviewModal\.vue'/)
  assert.match(videoNodeSource, /import VideoNodeFeedbackModals from '\.\/video\/VideoNodeFeedbackModals\.vue'/)
  assert.match(videoNodeSource, /<VideoNodePreviewModal\s+v-model:show="showPreviewModal"\s+:video-url="displayVideoUrl"\s*\/>/)
  assert.match(
    videoNodeSource,
    /<VideoNodeFeedbackModals\s+v-model:show-error="showErrorModal"\s+v-model:show-validation="showValidationModal"\s+:error-message="data\.error"\s+:validation-title="validationTitle"\s+:validation-message="validationMessage"\s+@close-error="closeErrorModal"\s+@close-validation="closeValidationModal"\s*\/>/
  )
  assert.doesNotMatch(videoNodeSource, /<n-modal/)
  assert.doesNotMatch(videoNodeSource, /class="zoom-modal-card"/)
  assert.doesNotMatch(videoNodeSource, /<BaseModal/)
  assert.doesNotMatch(videoNodeSource, /BaseButton|BaseModalActions|BaseModalCopy/)
  assert.doesNotMatch(videoNodeSource, /NModal/)
  assert.doesNotMatch(videoNodeSource, /\.zoom-modal-card\s*\{/)
  assert.doesNotMatch(videoNodeSource, /\.zoom-video-original\s*\{/)

  assert.match(previewModalSource, /import \{ NModal \} from 'naive-ui'/)
  assert.match(previewModalSource, /defineProps\(\{\s*show:/s)
  assert.match(previewModalSource, /videoUrl:/)
  assert.match(previewModalSource, /defineEmits\(\['update:show'\]\)/)
  assert.match(previewModalSource, /<n-modal\s+:show="show"\s+:mask-closable="true"/)
  assert.match(previewModalSource, /@update:show="\$emit\('update:show', \$event\)"/)
  assert.match(previewModalSource, /<video :src="videoUrl" controls autoplay class="zoom-video-original" \/>/)
  assert.match(previewModalSource, /\.zoom-modal-card\s*\{/)
  assert.match(previewModalSource, /\.zoom-video-original\s*\{/)

  assert.match(feedbackModalsSource, /import \{ BaseButton, BaseModal, BaseModalActions, BaseModalCopy \} from '@\/components\/ui'/)
  assert.match(feedbackModalsSource, /defineProps\(\{\s*showError:/s)
  assert.match(feedbackModalsSource, /validationTitle:/)
  assert.match(feedbackModalsSource, /defineEmits\(\['update:showError', 'update:showValidation', 'closeError', 'closeValidation'\]\)/)
  assert.match(feedbackModalsSource, /title="Video Module Error"/)
  assert.match(feedbackModalsSource, /<BaseModalCopy class="whitespace-pre-wrap">\{\{ errorMessage \}\}<\/BaseModalCopy>/)
  assert.match(feedbackModalsSource, /<BaseButton @click="\$emit\('closeError'\)">Close<\/BaseButton>/)
  assert.match(feedbackModalsSource, /:title="validationTitle"/)
  assert.match(feedbackModalsSource, /<BaseModalCopy class="whitespace-pre-wrap">\{\{ validationMessage \}\}<\/BaseModalCopy>/)
  assert.match(feedbackModalsSource, /<BaseButton @click="\$emit\('closeValidation'\)">OK<\/BaseButton>/)
})

test('video node delegates capsule toolbar to a focused component', () => {
  const capsuleMenuSource = readVideoComponentSource('VideoNodeCapsuleMenu')

  assert.match(videoNodeSource, /import VideoNodeCapsuleMenu from '\.\/video\/VideoNodeCapsuleMenu\.vue'/)
  assert.match(videoNodeSource, /<VideoNodeCapsuleMenu\s+v-show="showNodeCapsule"/)
  assert.match(videoNodeSource, /:capsule-style="capsuleStyle"/)
  assert.match(videoNodeSource, /:selected="isSelected"/)
  assert.match(videoNodeSource, /:model-options="modelOptions"/)
  assert.match(videoNodeSource, /:display-model="displayModel"/)
  assert.match(videoNodeSource, /:input-profile="inputProfile"/)
  assert.match(videoNodeSource, /:ratio-options="ratioOptions"/)
  assert.match(videoNodeSource, /:display-ratio="localRatio"/)
  assert.match(videoNodeSource, /:type-options="typeOptions"/)
  assert.match(videoNodeSource, /:display-o1-type="displayO1Type"/)
  assert.match(videoNodeSource, /:mode-options="modeOptions"/)
  assert.match(videoNodeSource, /:display-mode="displayMode"/)
  assert.match(videoNodeSource, /:size-options="sizeOptions"/)
  assert.match(videoNodeSource, /:display-size="displaySize"/)
  assert.match(videoNodeSource, /:resolution-options="resolutionOptions"/)
  assert.match(videoNodeSource, /:display-resolution="displayResolution"/)
  assert.match(videoNodeSource, /:supports-audio-toggle="supportsAudioToggle"/)
  assert.match(videoNodeSource, /:audio-options="audioOptions"/)
  assert.match(videoNodeSource, /:display-audio="displayAudio"/)
  assert.match(videoNodeSource, /:duration-options="durationOptions"/)
  assert.match(videoNodeSource, /:display-duration="localDuration"/)
  assert.match(videoNodeSource, /:tool-options="toolDropdownOptions"/)
  assert.match(videoNodeSource, /:tools-disabled="isToolsDisabled"/)
  assert.match(videoNodeSource, /:has-video="!!displayVideoUrl"/)
  assert.match(videoNodeSource, /:video-busy="isVideoBusy"/)
  assert.match(videoNodeSource, /@select-model="setModel"/)
  assert.match(videoNodeSource, /@select-ratio="setRatio"/)
  assert.match(videoNodeSource, /@select-o1-type="setO1Type"/)
  assert.match(videoNodeSource, /@select-mode="setMode"/)
  assert.match(videoNodeSource, /@select-size="setSize"/)
  assert.match(videoNodeSource, /@select-resolution="setResolution"/)
  assert.match(videoNodeSource, /@select-generate-audio="setGenerateAudio"/)
  assert.match(videoNodeSource, /@select-duration="setDuration"/)
  assert.match(videoNodeSource, /@tool-action="handleToolAction"/)
  assert.match(videoNodeSource, /@preview="openPreviewModal"/)
  assert.match(videoNodeSource, /@duplicate="handleDuplicate"/)
  assert.match(videoNodeSource, /@delete="handleDelete"/)
  assert.match(videoNodeSource, /@create="handleGenerateVideo"/)
  assert.match(videoNodeSource, /@regenerate="handleRegenerateVideo"/)
  assert.match(videoNodeSource, /@stop="handleStopGeneration"/)
  assert.doesNotMatch(videoNodeSource, /<BaseDropdown/)
  assert.doesNotMatch(videoNodeSource, /BaseDropdown/)
  assert.doesNotMatch(videoNodeSource, /class="capsule-menu/)
  assert.doesNotMatch(videoNodeSource, /createIcon|toolsIcon|CloseCircleOutline|CopyOutline|ExpandOutline|RefreshOutline|TrashOutline/)
  assert.doesNotMatch(videoNodeSource, /\.capsule-tool-trigger|\.capsule-tool-icon/)

  assert.match(capsuleMenuSource, /import \{ NIcon \} from 'naive-ui'/)
  assert.match(capsuleMenuSource, /import \{ BaseDropdown \} from '@\/components\/ui'/)
  assert.match(capsuleMenuSource, /import createIcon from '@\/assets\/create-icon\.svg'/)
  assert.match(capsuleMenuSource, /import toolsIcon from '@\/assets\/tools-icon\.svg'/)
  assert.match(capsuleMenuSource, /defineEmits\(\[\s*'selectModel'/s)
  assert.match(capsuleMenuSource, /class="capsule-menu absolute left-1\/2 z-\[1200\]"/)
  assert.match(capsuleMenuSource, /<BaseDropdown :options="modelOptions" compact @select="\$emit\('selectModel', \$event\)"/)
  assert.match(capsuleMenuSource, /v-if="inputProfile\.allowRatio"/)
  assert.match(capsuleMenuSource, /<BaseDropdown v-if="inputProfile\.allowType && typeOptions\.length > 0"/)
  assert.match(capsuleMenuSource, /<BaseDropdown v-if="inputProfile\.allowAudioToggle && supportsAudioToggle"/)
  assert.match(capsuleMenuSource, /<BaseDropdown :options="toolOptions" compact @select="\$emit\('toolAction', \$event\)"/)
  assert.match(capsuleMenuSource, /:disabled="toolsDisabled"/)
  assert.match(capsuleMenuSource, /:disabled="!hasVideo"/)
  assert.match(capsuleMenuSource, /@click="\$emit\('preview'\)"/)
  assert.match(capsuleMenuSource, /@click="\$emit\('duplicate'\)"/)
  assert.match(capsuleMenuSource, /@click="\$emit\('delete'\)"/)
  assert.match(capsuleMenuSource, /@click="\$emit\('create'\)"/)
  assert.match(capsuleMenuSource, /@click="\$emit\('regenerate'\)"/)
  assert.match(capsuleMenuSource, /@click="\$emit\('stop'\)"/)
  assert.match(capsuleMenuSource, /<style scoped src="\.\/\.\.\/node-base\.css"><\/style>/)
  assert.match(capsuleMenuSource, /\.capsule-tool-trigger\s*\{/)
  assert.match(capsuleMenuSource, /\.capsule-tool-icon\s*\{/)
})

test('video node delegates upload persistence and unload protection to a focused composable', () => {
  const uploadPersistenceSource = readVideoScriptSource('useVideoNodeUploadPersistence')

  assert.match(videoNodeSource, /import \{ useVideoNodeUploadPersistence \} from '\.\/video\/useVideoNodeUploadPersistence\.js'/)
  assert.match(videoNodeSource, /useVideoNodeUploadPersistence\(\{/)
  assert.match(videoNodeSource, /triggerUpload/)
  assert.match(videoNodeSource, /handleFileUpload/)
  assert.match(videoNodeSource, /uploadProgressStyle/)
  assert.doesNotMatch(videoNodeSource, /const beforeUnloadGuard = \(event\) =>/)
  assert.doesNotMatch(videoNodeSource, /window\.addEventListener\('beforeunload'/)
  assert.doesNotMatch(videoNodeSource, /window\.removeEventListener\('beforeunload'/)
  assert.doesNotMatch(videoNodeSource, /const triggerUpload = \(\) =>/)
  assert.doesNotMatch(videoNodeSource, /const resetUploadProgress = \(/)
  assert.doesNotMatch(videoNodeSource, /const handleFileUpload = async/)
  assert.doesNotMatch(videoNodeSource, /file\.size > MAX_UPLOAD_SIZE_BYTES/)
  assert.doesNotMatch(videoNodeSource, /uploadImageFile\(file,/)
  assert.doesNotMatch(videoNodeSource, /const uploadProgressStyle = computed/)

  assert.match(uploadPersistenceSource, /import \{ computed, getCurrentInstance, onUnmounted, ref, watch \} from 'vue'/)
  assert.match(uploadPersistenceSource, /export const useVideoNodeUploadPersistence = \(/)
  assert.match(uploadPersistenceSource, /const beforeUnloadGuard = \(event\) =>/)
  assert.match(uploadPersistenceSource, /addWindowEventListener\('beforeunload', beforeUnloadGuard\)/)
  assert.match(uploadPersistenceSource, /removeWindowEventListener\('beforeunload', beforeUnloadGuard\)/)
  assert.match(uploadPersistenceSource, /const triggerUpload = \(\) =>/)
  assert.match(uploadPersistenceSource, /const resetUploadProgress = \(/)
  assert.match(uploadPersistenceSource, /const handleFileUpload = async/)
  assert.match(uploadPersistenceSource, /uploadVideoFile\(file,/)
  assert.match(uploadPersistenceSource, /const uploadProgressStyle = computed/)
})

test('video node delegates enhance result orchestration to a focused composable', () => {
  const enhanceResultsSource = readVideoScriptSource('useVideoNodeEnhanceResults')

  assert.match(videoNodeSource, /import \{ useVideoNodeEnhanceResults \} from '\.\/video\/useVideoNodeEnhanceResults\.js'/)
  assert.match(videoNodeSource, /useVideoNodeEnhanceResults\(\{/)
  assert.match(videoNodeSource, /showEnhanceDrawer/)
  assert.match(videoNodeSource, /toolActionLoading/)
  assert.match(videoNodeSource, /handleToolAction/)
  assert.match(videoNodeSource, /handleEnhancePending/)
  assert.match(videoNodeSource, /handleEnhanceApply/)
  assert.match(videoNodeSource, /handleEnhanceError/)
  assert.doesNotMatch(videoNodeSource, /const pendingEnhancedNodeId = ref/)
  assert.doesNotMatch(videoNodeSource, /const createLinkedVideoNode = \(/)
  assert.doesNotMatch(videoNodeSource, /const updateLinkedVideoNode = async/)
  assert.doesNotMatch(videoNodeSource, /const resolveVideoPersistence = async/)
  assert.doesNotMatch(videoNodeSource, /const handleToolAction = async/)
  assert.doesNotMatch(videoNodeSource, /const handleEnhancePending = async/)
  assert.doesNotMatch(videoNodeSource, /const handleEnhanceApply = async/)
  assert.doesNotMatch(videoNodeSource, /const handleEnhanceError = async/)

  assert.match(enhanceResultsSource, /import \{ ref \} from 'vue'/)
  assert.match(enhanceResultsSource, /export const useVideoNodeEnhanceResults = \(/)
  assert.match(enhanceResultsSource, /getCanvasAutoPlacementPosition/)
  assert.match(enhanceResultsSource, /const createData = \{\s*url: '',\s*loading: true,\s*label: 'Enhanced video',\s*\.\.\.payload\s*\}/s)
  assert.match(enhanceResultsSource, /const position = getCanvasAutoPlacementPosition\(\{/)
  assert.match(enhanceResultsSource, /existingNodes: readReactiveValue\(nodes\) \|\| \[\]/)
  assert.match(enhanceResultsSource, /const createLinkedVideoNode = \(/)
  assert.match(enhanceResultsSource, /const updateLinkedVideoNode = async/)
  assert.match(enhanceResultsSource, /const resolveVideoPersistence = async/)
  assert.match(enhanceResultsSource, /const handleToolAction = async/)
  assert.match(enhanceResultsSource, /const handleEnhancePending = async/)
  assert.match(enhanceResultsSource, /const handleEnhanceApply = async/)
  assert.match(enhanceResultsSource, /const handleEnhanceError = async/)
})
